// Generated by gencpp from file tron2_manipulation/arm_moveRequest.msg
// DO NOT EDIT!


#ifndef TRON2_MANIPULATION_MESSAGE_ARM_MOVEREQUEST_H
#define TRON2_MANIPULATION_MESSAGE_ARM_MOVEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tron2_manipulation
{
template <class ContainerAllocator>
struct arm_moveRequest_
{
  typedef arm_moveRequest_<ContainerAllocator> Type;

  arm_moveRequest_()
    : left_arm_pos()
    , right_arm_pos()
    , speed(0.0)  {
      left_arm_pos.assign(0.0);

      right_arm_pos.assign(0.0);
  }
  arm_moveRequest_(const ContainerAllocator& _alloc)
    : left_arm_pos()
    , right_arm_pos()
    , speed(0.0)  {
  (void)_alloc;
      left_arm_pos.assign(0.0);

      right_arm_pos.assign(0.0);
  }



   typedef boost::array<float, 7>  _left_arm_pos_type;
  _left_arm_pos_type left_arm_pos;

   typedef boost::array<float, 7>  _right_arm_pos_type;
  _right_arm_pos_type right_arm_pos;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::tron2_manipulation::arm_moveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tron2_manipulation::arm_moveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct arm_moveRequest_

typedef ::tron2_manipulation::arm_moveRequest_<std::allocator<void> > arm_moveRequest;

typedef boost::shared_ptr< ::tron2_manipulation::arm_moveRequest > arm_moveRequestPtr;
typedef boost::shared_ptr< ::tron2_manipulation::arm_moveRequest const> arm_moveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tron2_manipulation::arm_moveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tron2_manipulation::arm_moveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tron2_manipulation::arm_moveRequest_<ContainerAllocator1> & lhs, const ::tron2_manipulation::arm_moveRequest_<ContainerAllocator2> & rhs)
{
  return lhs.left_arm_pos == rhs.left_arm_pos &&
    lhs.right_arm_pos == rhs.right_arm_pos &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tron2_manipulation::arm_moveRequest_<ContainerAllocator1> & lhs, const ::tron2_manipulation::arm_moveRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tron2_manipulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tron2_manipulation::arm_moveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tron2_manipulation::arm_moveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tron2_manipulation::arm_moveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tron2_manipulation::arm_moveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tron2_manipulation::arm_moveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tron2_manipulation::arm_moveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tron2_manipulation::arm_moveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1deecaeea6f13a7b726cd7a09cbd7271";
  }

  static const char* value(const ::tron2_manipulation::arm_moveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1deecaeea6f13a7bULL;
  static const uint64_t static_value2 = 0x726cd7a09cbd7271ULL;
};

template<class ContainerAllocator>
struct DataType< ::tron2_manipulation::arm_moveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tron2_manipulation/arm_moveRequest";
  }

  static const char* value(const ::tron2_manipulation::arm_moveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tron2_manipulation::arm_moveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[7] left_arm_pos # [px py pz Qx Qy Qz Qw] unit: m\n"
"float32[7] right_arm_pos # [px py pz Qx Qy Qz Qw] unit: m\n"
"# speed\n"
"float32 speed # unit: rad/s or m/s\n"
;
  }

  static const char* value(const ::tron2_manipulation::arm_moveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tron2_manipulation::arm_moveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_arm_pos);
      stream.next(m.right_arm_pos);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arm_moveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tron2_manipulation::arm_moveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tron2_manipulation::arm_moveRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "left_arm_pos: ";
    if (v.left_arm_pos.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.left_arm_pos.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.left_arm_pos[i]);
    }
    if (v.left_arm_pos.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_arm_pos: ";
    if (v.right_arm_pos.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.right_arm_pos.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.right_arm_pos[i]);
    }
    if (v.right_arm_pos.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRON2_MANIPULATION_MESSAGE_ARM_MOVEREQUEST_H
