// Generated by gencpp from file hand_msgs/HandState.msg
// DO NOT EDIT!


#ifndef HAND_MSGS_MESSAGE_HANDSTATE_H
#define HAND_MSGS_MESSAGE_HANDSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <hand_msgs/HandMsg.h>

namespace hand_msgs
{
template <class ContainerAllocator>
struct HandState_
{
  typedef HandState_<ContainerAllocator> Type;

  HandState_()
    : header()
    , hand_type()
    , ctrl_mode()
    , hand_state()  {
      ctrl_mode.assign(0);
  }
  HandState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , hand_type(_alloc)
    , ctrl_mode()
    , hand_state()  {
  (void)_alloc;
      ctrl_mode.assign(0);

      hand_state.assign( ::hand_msgs::HandMsg_<ContainerAllocator> (_alloc));
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _hand_type_type;
  _hand_type_type hand_type;

   typedef boost::array<uint8_t, 2>  _ctrl_mode_type;
  _ctrl_mode_type ctrl_mode;

   typedef boost::array< ::hand_msgs::HandMsg_<ContainerAllocator> , 2>  _hand_state_type;
  _hand_state_type hand_state;





  typedef boost::shared_ptr< ::hand_msgs::HandState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_msgs::HandState_<ContainerAllocator> const> ConstPtr;

}; // struct HandState_

typedef ::hand_msgs::HandState_<std::allocator<void> > HandState;

typedef boost::shared_ptr< ::hand_msgs::HandState > HandStatePtr;
typedef boost::shared_ptr< ::hand_msgs::HandState const> HandStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_msgs::HandState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_msgs::HandState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hand_msgs::HandState_<ContainerAllocator1> & lhs, const ::hand_msgs::HandState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.hand_type == rhs.hand_type &&
    lhs.ctrl_mode == rhs.ctrl_mode &&
    lhs.hand_state == rhs.hand_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hand_msgs::HandState_<ContainerAllocator1> & lhs, const ::hand_msgs::HandState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hand_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hand_msgs::HandState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_msgs::HandState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_msgs::HandState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_msgs::HandState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_msgs::HandState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_msgs::HandState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_msgs::HandState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e859982707a5c9b2e1da5a16bffb891";
  }

  static const char* value(const ::hand_msgs::HandState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e859982707a5c9bULL;
  static const uint64_t static_value2 = 0x2e1da5a16bffb891ULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_msgs::HandState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_msgs/HandState";
  }

  static const char* value(const ::hand_msgs::HandState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_msgs::HandState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string hand_type\n"
"\n"
"uint8[2] ctrl_mode\n"
"\n"
"HandMsg[2] hand_state\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: hand_msgs/HandMsg\n"
"std_msgs/Header header\n"
"\n"
"string[]  names\n"
"float32[] pos\n"
"float32[] vel\n"
"float32[] current\n"
"float32[] time\n"
;
  }

  static const char* value(const ::hand_msgs::HandState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_msgs::HandState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.hand_type);
      stream.next(m.ctrl_mode);
      stream.next(m.hand_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HandState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_msgs::HandState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_msgs::HandState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hand_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.hand_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ctrl_mode: ";
    if (v.ctrl_mode.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.ctrl_mode.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.ctrl_mode[i]);
    }
    if (v.ctrl_mode.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hand_state: ";
    if (v.hand_state.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.hand_state.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::hand_msgs::HandMsg_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.hand_state[i]);
    }
    if (v.hand_state.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_MSGS_MESSAGE_HANDSTATE_H
