// Generated by gencpp from file std_msgs/ByteArray.msg
// DO NOT EDIT!


#ifndef STD_MSGS_MESSAGE_BYTEARRAY_H
#define STD_MSGS_MESSAGE_BYTEARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace std_msgs
{
template <class ContainerAllocator>
struct ByteArray_
{
  typedef ByteArray_<ContainerAllocator> Type;

  ByteArray_()
    : header()
    , data()  {
    }
  ByteArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::std_msgs::ByteArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::std_msgs::ByteArray_<ContainerAllocator> const> ConstPtr;

}; // struct ByteArray_

typedef ::std_msgs::ByteArray_<std::allocator<void> > ByteArray;

typedef boost::shared_ptr< ::std_msgs::ByteArray > ByteArrayPtr;
typedef boost::shared_ptr< ::std_msgs::ByteArray const> ByteArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::std_msgs::ByteArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::std_msgs::ByteArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::std_msgs::ByteArray_<ContainerAllocator1> & lhs, const ::std_msgs::ByteArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::std_msgs::ByteArray_<ContainerAllocator1> & lhs, const ::std_msgs::ByteArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace std_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::std_msgs::ByteArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::std_msgs::ByteArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_msgs::ByteArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_msgs::ByteArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_msgs::ByteArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_msgs::ByteArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::std_msgs::ByteArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a80b57fc88eea2f0cd76ef6a9312f0b";
  }

  static const char* value(const ::std_msgs::ByteArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a80b57fc88eea2fULL;
  static const uint64_t static_value2 = 0x0cd76ef6a9312f0bULL;
};

template<class ContainerAllocator>
struct DataType< ::std_msgs::ByteArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/ByteArray";
  }

  static const char* value(const ::std_msgs::ByteArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::std_msgs::ByteArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header  header   # header info\n"
"byte[]  data     # array of data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::std_msgs::ByteArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::std_msgs::ByteArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ByteArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::std_msgs::ByteArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::std_msgs::ByteArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int8_t>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // STD_MSGS_MESSAGE_BYTEARRAY_H
