# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from upper_body/arm_servo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class arm_servo(genpy.Message):
  _md5sum = "97e96a0b33437f001f2d5b69b43cfc77"
  _type = "upper_body/arm_servo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string servo_type # servoJ or servoP
# servoJ
float32[] left_arm_joints # unit: rad
float32[] right_arm_joints # unit: rad
# servoP
float32[7] left_arm_pos # [px py pz Qx Qy Qz Qw] unit: m
float32[7] right_arm_pos # [px py pz Qx Qy Qz Qw] unit: mz
"""
  __slots__ = ['servo_type','left_arm_joints','right_arm_joints','left_arm_pos','right_arm_pos']
  _slot_types = ['string','float32[]','float32[]','float32[7]','float32[7]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       servo_type,left_arm_joints,right_arm_joints,left_arm_pos,right_arm_pos

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(arm_servo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.servo_type is None:
        self.servo_type = ''
      if self.left_arm_joints is None:
        self.left_arm_joints = []
      if self.right_arm_joints is None:
        self.right_arm_joints = []
      if self.left_arm_pos is None:
        self.left_arm_pos = [0.] * 7
      if self.right_arm_pos is None:
        self.right_arm_pos = [0.] * 7
    else:
      self.servo_type = ''
      self.left_arm_joints = []
      self.right_arm_joints = []
      self.left_arm_pos = [0.] * 7
      self.right_arm_pos = [0.] * 7

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.servo_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.left_arm_joints)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.left_arm_joints))
      length = len(self.right_arm_joints)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.right_arm_joints))
      buff.write(_get_struct_7f().pack(*self.left_arm_pos))
      buff.write(_get_struct_7f().pack(*self.right_arm_pos))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.servo_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.servo_type = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.left_arm_joints = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.right_arm_joints = s.unpack(str[start:end])
      start = end
      end += 28
      self.left_arm_pos = _get_struct_7f().unpack(str[start:end])
      start = end
      end += 28
      self.right_arm_pos = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.servo_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.left_arm_joints)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.left_arm_joints.tostring())
      length = len(self.right_arm_joints)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.right_arm_joints.tostring())
      buff.write(self.left_arm_pos.tostring())
      buff.write(self.right_arm_pos.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.servo_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.servo_type = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.left_arm_joints = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.right_arm_joints = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 28
      self.left_arm_pos = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
      start = end
      end += 28
      self.right_arm_pos = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7f = None
def _get_struct_7f():
    global _struct_7f
    if _struct_7f is None:
        _struct_7f = struct.Struct("<7f")
    return _struct_7f
