// Generated by gencpp from file std_srvs/GetBoolWithTile.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_GETBOOLWITHTILE_H
#define STD_SRVS_MESSAGE_GETBOOLWITHTILE_H

#include <ros/service_traits.h>


#include <std_srvs/GetBoolWithTileRequest.h>
#include <std_srvs/GetBoolWithTileResponse.h>


namespace std_srvs
{

struct GetBoolWithTile
{

typedef GetBoolWithTileRequest Request;
typedef GetBoolWithTileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBoolWithTile
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::GetBoolWithTile > {
  static const char* value()
  {
    return "9249c32b355c3c3418b36019eafdd629";
  }

  static const char* value(const ::std_srvs::GetBoolWithTile&) { return value(); }
};

template<>
struct DataType< ::std_srvs::GetBoolWithTile > {
  static const char* value()
  {
    return "std_srvs/GetBoolWithTile";
  }

  static const char* value(const ::std_srvs::GetBoolWithTile&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::GetBoolWithTileRequest> should match
// service_traits::MD5Sum< ::std_srvs::GetBoolWithTile >
template<>
struct MD5Sum< ::std_srvs::GetBoolWithTileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetBoolWithTile >::value();
  }
  static const char* value(const ::std_srvs::GetBoolWithTileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetBoolWithTileRequest> should match
// service_traits::DataType< ::std_srvs::GetBoolWithTile >
template<>
struct DataType< ::std_srvs::GetBoolWithTileRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetBoolWithTile >::value();
  }
  static const char* value(const ::std_srvs::GetBoolWithTileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::GetBoolWithTileResponse> should match
// service_traits::MD5Sum< ::std_srvs::GetBoolWithTile >
template<>
struct MD5Sum< ::std_srvs::GetBoolWithTileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetBoolWithTile >::value();
  }
  static const char* value(const ::std_srvs::GetBoolWithTileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetBoolWithTileResponse> should match
// service_traits::DataType< ::std_srvs::GetBoolWithTile >
template<>
struct DataType< ::std_srvs::GetBoolWithTileResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetBoolWithTile >::value();
  }
  static const char* value(const ::std_srvs::GetBoolWithTileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_GETBOOLWITHTILE_H
