// Generated by gencpp from file std_srvs/GetFloat32Array.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_GETFLOAT32ARRAY_H
#define STD_SRVS_MESSAGE_GETFLOAT32ARRAY_H

#include <ros/service_traits.h>


#include <std_srvs/GetFloat32ArrayRequest.h>
#include <std_srvs/GetFloat32ArrayResponse.h>


namespace std_srvs
{

struct GetFloat32Array
{

typedef GetFloat32ArrayRequest Request;
typedef GetFloat32ArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFloat32Array
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::GetFloat32Array > {
  static const char* value()
  {
    return "9b3e91babdca48b3b67f859255eb7eaa";
  }

  static const char* value(const ::std_srvs::GetFloat32Array&) { return value(); }
};

template<>
struct DataType< ::std_srvs::GetFloat32Array > {
  static const char* value()
  {
    return "std_srvs/GetFloat32Array";
  }

  static const char* value(const ::std_srvs::GetFloat32Array&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::GetFloat32ArrayRequest> should match
// service_traits::MD5Sum< ::std_srvs::GetFloat32Array >
template<>
struct MD5Sum< ::std_srvs::GetFloat32ArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetFloat32Array >::value();
  }
  static const char* value(const ::std_srvs::GetFloat32ArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetFloat32ArrayRequest> should match
// service_traits::DataType< ::std_srvs::GetFloat32Array >
template<>
struct DataType< ::std_srvs::GetFloat32ArrayRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetFloat32Array >::value();
  }
  static const char* value(const ::std_srvs::GetFloat32ArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::GetFloat32ArrayResponse> should match
// service_traits::MD5Sum< ::std_srvs::GetFloat32Array >
template<>
struct MD5Sum< ::std_srvs::GetFloat32ArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetFloat32Array >::value();
  }
  static const char* value(const ::std_srvs::GetFloat32ArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetFloat32ArrayResponse> should match
// service_traits::DataType< ::std_srvs::GetFloat32Array >
template<>
struct DataType< ::std_srvs::GetFloat32ArrayResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetFloat32Array >::value();
  }
  static const char* value(const ::std_srvs::GetFloat32ArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_GETFLOAT32ARRAY_H
