// Generated by gencpp from file std_srvs/GetStringArrayWithTitle.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_GETSTRINGARRAYWITHTITLE_H
#define STD_SRVS_MESSAGE_GETSTRINGARRAYWITHTITLE_H

#include <ros/service_traits.h>


#include <std_srvs/GetStringArrayWithTitleRequest.h>
#include <std_srvs/GetStringArrayWithTitleResponse.h>


namespace std_srvs
{

struct GetStringArrayWithTitle
{

typedef GetStringArrayWithTitleRequest Request;
typedef GetStringArrayWithTitleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetStringArrayWithTitle
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::GetStringArrayWithTitle > {
  static const char* value()
  {
    return "bb72c643575c1e3ad2b1ece3bf121925";
  }

  static const char* value(const ::std_srvs::GetStringArrayWithTitle&) { return value(); }
};

template<>
struct DataType< ::std_srvs::GetStringArrayWithTitle > {
  static const char* value()
  {
    return "std_srvs/GetStringArrayWithTitle";
  }

  static const char* value(const ::std_srvs::GetStringArrayWithTitle&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::GetStringArrayWithTitleRequest> should match
// service_traits::MD5Sum< ::std_srvs::GetStringArrayWithTitle >
template<>
struct MD5Sum< ::std_srvs::GetStringArrayWithTitleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetStringArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::GetStringArrayWithTitleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetStringArrayWithTitleRequest> should match
// service_traits::DataType< ::std_srvs::GetStringArrayWithTitle >
template<>
struct DataType< ::std_srvs::GetStringArrayWithTitleRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetStringArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::GetStringArrayWithTitleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::GetStringArrayWithTitleResponse> should match
// service_traits::MD5Sum< ::std_srvs::GetStringArrayWithTitle >
template<>
struct MD5Sum< ::std_srvs::GetStringArrayWithTitleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetStringArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::GetStringArrayWithTitleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetStringArrayWithTitleResponse> should match
// service_traits::DataType< ::std_srvs::GetStringArrayWithTitle >
template<>
struct DataType< ::std_srvs::GetStringArrayWithTitleResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetStringArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::GetStringArrayWithTitleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_GETSTRINGARRAYWITHTITLE_H
