// Generated by gencpp from file std_srvs/GetUint32Array.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_GETUINT32ARRAY_H
#define STD_SRVS_MESSAGE_GETUINT32ARRAY_H

#include <ros/service_traits.h>


#include <std_srvs/GetUint32ArrayRequest.h>
#include <std_srvs/GetUint32ArrayResponse.h>


namespace std_srvs
{

struct GetUint32Array
{

typedef GetUint32ArrayRequest Request;
typedef GetUint32ArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetUint32Array
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::GetUint32Array > {
  static const char* value()
  {
    return "64a7289ff26fd15c6086810950c31b58";
  }

  static const char* value(const ::std_srvs::GetUint32Array&) { return value(); }
};

template<>
struct DataType< ::std_srvs::GetUint32Array > {
  static const char* value()
  {
    return "std_srvs/GetUint32Array";
  }

  static const char* value(const ::std_srvs::GetUint32Array&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::GetUint32ArrayRequest> should match
// service_traits::MD5Sum< ::std_srvs::GetUint32Array >
template<>
struct MD5Sum< ::std_srvs::GetUint32ArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetUint32Array >::value();
  }
  static const char* value(const ::std_srvs::GetUint32ArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetUint32ArrayRequest> should match
// service_traits::DataType< ::std_srvs::GetUint32Array >
template<>
struct DataType< ::std_srvs::GetUint32ArrayRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetUint32Array >::value();
  }
  static const char* value(const ::std_srvs::GetUint32ArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::GetUint32ArrayResponse> should match
// service_traits::MD5Sum< ::std_srvs::GetUint32Array >
template<>
struct MD5Sum< ::std_srvs::GetUint32ArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetUint32Array >::value();
  }
  static const char* value(const ::std_srvs::GetUint32ArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetUint32ArrayResponse> should match
// service_traits::DataType< ::std_srvs::GetUint32Array >
template<>
struct DataType< ::std_srvs::GetUint32ArrayResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetUint32Array >::value();
  }
  static const char* value(const ::std_srvs::GetUint32ArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_GETUINT32ARRAY_H
