// Generated by gencpp from file std_srvs/SetBoolWithTitleResponse.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETBOOLWITHTITLERESPONSE_H
#define STD_SRVS_MESSAGE_SETBOOLWITHTITLERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace std_srvs
{
template <class ContainerAllocator>
struct SetBoolWithTitleResponse_
{
  typedef SetBoolWithTitleResponse_<ContainerAllocator> Type;

  SetBoolWithTitleResponse_()
    : success(false)
    , message()  {
    }
  SetBoolWithTitleResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetBoolWithTitleResponse_

typedef ::std_srvs::SetBoolWithTitleResponse_<std::allocator<void> > SetBoolWithTitleResponse;

typedef boost::shared_ptr< ::std_srvs::SetBoolWithTitleResponse > SetBoolWithTitleResponsePtr;
typedef boost::shared_ptr< ::std_srvs::SetBoolWithTitleResponse const> SetBoolWithTitleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator1> & lhs, const ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator1> & lhs, const ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace std_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_srvs/SetBoolWithTitleResponse";
  }

  static const char* value(const ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success   # indicate successful run of triggered service\n"
"string message # informational, e.g. for error messages\n"
"\n"
;
  }

  static const char* value(const ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetBoolWithTitleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::std_srvs::SetBoolWithTitleResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETBOOLWITHTITLERESPONSE_H
