// Generated by gencpp from file std_srvs/SetFloat32.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETFLOAT32_H
#define STD_SRVS_MESSAGE_SETFLOAT32_H

#include <ros/service_traits.h>


#include <std_srvs/SetFloat32Request.h>
#include <std_srvs/SetFloat32Response.h>


namespace std_srvs
{

struct SetFloat32
{

typedef SetFloat32Request Request;
typedef SetFloat32Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloat32
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::SetFloat32 > {
  static const char* value()
  {
    return "96fbe2a49585a736ad8b4a31afbaf099";
  }

  static const char* value(const ::std_srvs::SetFloat32&) { return value(); }
};

template<>
struct DataType< ::std_srvs::SetFloat32 > {
  static const char* value()
  {
    return "std_srvs/SetFloat32";
  }

  static const char* value(const ::std_srvs::SetFloat32&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::SetFloat32Request> should match
// service_traits::MD5Sum< ::std_srvs::SetFloat32 >
template<>
struct MD5Sum< ::std_srvs::SetFloat32Request>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetFloat32 >::value();
  }
  static const char* value(const ::std_srvs::SetFloat32Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetFloat32Request> should match
// service_traits::DataType< ::std_srvs::SetFloat32 >
template<>
struct DataType< ::std_srvs::SetFloat32Request>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetFloat32 >::value();
  }
  static const char* value(const ::std_srvs::SetFloat32Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::SetFloat32Response> should match
// service_traits::MD5Sum< ::std_srvs::SetFloat32 >
template<>
struct MD5Sum< ::std_srvs::SetFloat32Response>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetFloat32 >::value();
  }
  static const char* value(const ::std_srvs::SetFloat32Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetFloat32Response> should match
// service_traits::DataType< ::std_srvs::SetFloat32 >
template<>
struct DataType< ::std_srvs::SetFloat32Response>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetFloat32 >::value();
  }
  static const char* value(const ::std_srvs::SetFloat32Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETFLOAT32_H
