// Generated by gencpp from file std_srvs/SetFloat64ArrayWithTitle.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETFLOAT64ARRAYWITHTITLE_H
#define STD_SRVS_MESSAGE_SETFLOAT64ARRAYWITHTITLE_H

#include <ros/service_traits.h>


#include <std_srvs/SetFloat64ArrayWithTitleRequest.h>
#include <std_srvs/SetFloat64ArrayWithTitleResponse.h>


namespace std_srvs
{

struct SetFloat64ArrayWithTitle
{

typedef SetFloat64ArrayWithTitleRequest Request;
typedef SetFloat64ArrayWithTitleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloat64ArrayWithTitle
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::SetFloat64ArrayWithTitle > {
  static const char* value()
  {
    return "df55ab8abe7dc128d949e1c0d94b9867";
  }

  static const char* value(const ::std_srvs::SetFloat64ArrayWithTitle&) { return value(); }
};

template<>
struct DataType< ::std_srvs::SetFloat64ArrayWithTitle > {
  static const char* value()
  {
    return "std_srvs/SetFloat64ArrayWithTitle";
  }

  static const char* value(const ::std_srvs::SetFloat64ArrayWithTitle&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::SetFloat64ArrayWithTitleRequest> should match
// service_traits::MD5Sum< ::std_srvs::SetFloat64ArrayWithTitle >
template<>
struct MD5Sum< ::std_srvs::SetFloat64ArrayWithTitleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetFloat64ArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetFloat64ArrayWithTitleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetFloat64ArrayWithTitleRequest> should match
// service_traits::DataType< ::std_srvs::SetFloat64ArrayWithTitle >
template<>
struct DataType< ::std_srvs::SetFloat64ArrayWithTitleRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetFloat64ArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetFloat64ArrayWithTitleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::SetFloat64ArrayWithTitleResponse> should match
// service_traits::MD5Sum< ::std_srvs::SetFloat64ArrayWithTitle >
template<>
struct MD5Sum< ::std_srvs::SetFloat64ArrayWithTitleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetFloat64ArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetFloat64ArrayWithTitleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetFloat64ArrayWithTitleResponse> should match
// service_traits::DataType< ::std_srvs::SetFloat64ArrayWithTitle >
template<>
struct DataType< ::std_srvs::SetFloat64ArrayWithTitleResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetFloat64ArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetFloat64ArrayWithTitleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETFLOAT64ARRAYWITHTITLE_H
