// Generated by gencpp from file std_srvs/SetFloat32ArrayWithTitleRequest.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETFLOAT32ARRAYWITHTITLEREQUEST_H
#define STD_SRVS_MESSAGE_SETFLOAT32ARRAYWITHTITLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace std_srvs
{
template <class ContainerAllocator>
struct SetFloat32ArrayWithTitleRequest_
{
  typedef SetFloat32ArrayWithTitleRequest_<ContainerAllocator> Type;

  SetFloat32ArrayWithTitleRequest_()
    : title()
    , data()  {
    }
  SetFloat32ArrayWithTitleRequest_(const ContainerAllocator& _alloc)
    : title(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _title_type;
  _title_type title;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetFloat32ArrayWithTitleRequest_

typedef ::std_srvs::SetFloat32ArrayWithTitleRequest_<std::allocator<void> > SetFloat32ArrayWithTitleRequest;

typedef boost::shared_ptr< ::std_srvs::SetFloat32ArrayWithTitleRequest > SetFloat32ArrayWithTitleRequestPtr;
typedef boost::shared_ptr< ::std_srvs::SetFloat32ArrayWithTitleRequest const> SetFloat32ArrayWithTitleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator1> & lhs, const ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.title == rhs.title &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator1> & lhs, const ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace std_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6fb7ce2b1214bd1ade6143698f0962b4";
  }

  static const char* value(const ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6fb7ce2b1214bd1aULL;
  static const uint64_t static_value2 = 0xde6143698f0962b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_srvs/SetFloat32ArrayWithTitleRequest";
  }

  static const char* value(const ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string title\n"
"float32[]  data     # array of data\n"
;
  }

  static const char* value(const ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.title);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetFloat32ArrayWithTitleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::std_srvs::SetFloat32ArrayWithTitleRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "title: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.title);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETFLOAT32ARRAYWITHTITLEREQUEST_H
