// Generated by gencpp from file std_srvs/SetInt32WithTitleRequest.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETINT32WITHTITLEREQUEST_H
#define STD_SRVS_MESSAGE_SETINT32WITHTITLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace std_srvs
{
template <class ContainerAllocator>
struct SetInt32WithTitleRequest_
{
  typedef SetInt32WithTitleRequest_<ContainerAllocator> Type;

  SetInt32WithTitleRequest_()
    : title()
    , data(0)  {
    }
  SetInt32WithTitleRequest_(const ContainerAllocator& _alloc)
    : title(_alloc)
    , data(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _title_type;
  _title_type title;

   typedef int32_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetInt32WithTitleRequest_

typedef ::std_srvs::SetInt32WithTitleRequest_<std::allocator<void> > SetInt32WithTitleRequest;

typedef boost::shared_ptr< ::std_srvs::SetInt32WithTitleRequest > SetInt32WithTitleRequestPtr;
typedef boost::shared_ptr< ::std_srvs::SetInt32WithTitleRequest const> SetInt32WithTitleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator1> & lhs, const ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.title == rhs.title &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator1> & lhs, const ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace std_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1bd12f774fd9ca7c1053901fe41f252a";
  }

  static const char* value(const ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1bd12f774fd9ca7cULL;
  static const uint64_t static_value2 = 0x1053901fe41f252aULL;
};

template<class ContainerAllocator>
struct DataType< ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_srvs/SetInt32WithTitleRequest";
  }

  static const char* value(const ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string title\n"
"int32 data\n"
;
  }

  static const char* value(const ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.title);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetInt32WithTitleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::std_srvs::SetInt32WithTitleRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "title: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.title);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETINT32WITHTITLEREQUEST_H
