// Generated by gencpp from file std_srvs/SetInt32WithTitle.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETINT32WITHTITLE_H
#define STD_SRVS_MESSAGE_SETINT32WITHTITLE_H

#include <ros/service_traits.h>


#include <std_srvs/SetInt32WithTitleRequest.h>
#include <std_srvs/SetInt32WithTitleResponse.h>


namespace std_srvs
{

struct SetInt32WithTitle
{

typedef SetInt32WithTitleRequest Request;
typedef SetInt32WithTitleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInt32WithTitle
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::SetInt32WithTitle > {
  static const char* value()
  {
    return "04eab31200ddf4bba578f838361b709a";
  }

  static const char* value(const ::std_srvs::SetInt32WithTitle&) { return value(); }
};

template<>
struct DataType< ::std_srvs::SetInt32WithTitle > {
  static const char* value()
  {
    return "std_srvs/SetInt32WithTitle";
  }

  static const char* value(const ::std_srvs::SetInt32WithTitle&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::SetInt32WithTitleRequest> should match
// service_traits::MD5Sum< ::std_srvs::SetInt32WithTitle >
template<>
struct MD5Sum< ::std_srvs::SetInt32WithTitleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetInt32WithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetInt32WithTitleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetInt32WithTitleRequest> should match
// service_traits::DataType< ::std_srvs::SetInt32WithTitle >
template<>
struct DataType< ::std_srvs::SetInt32WithTitleRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetInt32WithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetInt32WithTitleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::SetInt32WithTitleResponse> should match
// service_traits::MD5Sum< ::std_srvs::SetInt32WithTitle >
template<>
struct MD5Sum< ::std_srvs::SetInt32WithTitleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetInt32WithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetInt32WithTitleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetInt32WithTitleResponse> should match
// service_traits::DataType< ::std_srvs::SetInt32WithTitle >
template<>
struct DataType< ::std_srvs::SetInt32WithTitleResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetInt32WithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetInt32WithTitleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETINT32WITHTITLE_H
