// Generated by gencpp from file std_srvs/SetInt32ArrayWithTitle.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETINT32ARRAYWITHTITLE_H
#define STD_SRVS_MESSAGE_SETINT32ARRAYWITHTITLE_H

#include <ros/service_traits.h>


#include <std_srvs/SetInt32ArrayWithTitleRequest.h>
#include <std_srvs/SetInt32ArrayWithTitleResponse.h>


namespace std_srvs
{

struct SetInt32ArrayWithTitle
{

typedef SetInt32ArrayWithTitleRequest Request;
typedef SetInt32ArrayWithTitleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInt32ArrayWithTitle
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::SetInt32ArrayWithTitle > {
  static const char* value()
  {
    return "d9c68c784b1060cc05cbd5cbd4bb2f2f";
  }

  static const char* value(const ::std_srvs::SetInt32ArrayWithTitle&) { return value(); }
};

template<>
struct DataType< ::std_srvs::SetInt32ArrayWithTitle > {
  static const char* value()
  {
    return "std_srvs/SetInt32ArrayWithTitle";
  }

  static const char* value(const ::std_srvs::SetInt32ArrayWithTitle&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::SetInt32ArrayWithTitleRequest> should match
// service_traits::MD5Sum< ::std_srvs::SetInt32ArrayWithTitle >
template<>
struct MD5Sum< ::std_srvs::SetInt32ArrayWithTitleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetInt32ArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetInt32ArrayWithTitleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetInt32ArrayWithTitleRequest> should match
// service_traits::DataType< ::std_srvs::SetInt32ArrayWithTitle >
template<>
struct DataType< ::std_srvs::SetInt32ArrayWithTitleRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetInt32ArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetInt32ArrayWithTitleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::SetInt32ArrayWithTitleResponse> should match
// service_traits::MD5Sum< ::std_srvs::SetInt32ArrayWithTitle >
template<>
struct MD5Sum< ::std_srvs::SetInt32ArrayWithTitleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetInt32ArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetInt32ArrayWithTitleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetInt32ArrayWithTitleResponse> should match
// service_traits::DataType< ::std_srvs::SetInt32ArrayWithTitle >
template<>
struct DataType< ::std_srvs::SetInt32ArrayWithTitleResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetInt32ArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetInt32ArrayWithTitleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETINT32ARRAYWITHTITLE_H
