// Generated by gencpp from file std_srvs/SetUint8Array.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETUINT8ARRAY_H
#define STD_SRVS_MESSAGE_SETUINT8ARRAY_H

#include <ros/service_traits.h>


#include <std_srvs/SetUint8ArrayRequest.h>
#include <std_srvs/SetUint8ArrayResponse.h>


namespace std_srvs
{

struct SetUint8Array
{

typedef SetUint8ArrayRequest Request;
typedef SetUint8ArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetUint8Array
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::SetUint8Array > {
  static const char* value()
  {
    return "384ad86502b817c951ed61de6ab8c366";
  }

  static const char* value(const ::std_srvs::SetUint8Array&) { return value(); }
};

template<>
struct DataType< ::std_srvs::SetUint8Array > {
  static const char* value()
  {
    return "std_srvs/SetUint8Array";
  }

  static const char* value(const ::std_srvs::SetUint8Array&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::SetUint8ArrayRequest> should match
// service_traits::MD5Sum< ::std_srvs::SetUint8Array >
template<>
struct MD5Sum< ::std_srvs::SetUint8ArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetUint8Array >::value();
  }
  static const char* value(const ::std_srvs::SetUint8ArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetUint8ArrayRequest> should match
// service_traits::DataType< ::std_srvs::SetUint8Array >
template<>
struct DataType< ::std_srvs::SetUint8ArrayRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetUint8Array >::value();
  }
  static const char* value(const ::std_srvs::SetUint8ArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::SetUint8ArrayResponse> should match
// service_traits::MD5Sum< ::std_srvs::SetUint8Array >
template<>
struct MD5Sum< ::std_srvs::SetUint8ArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetUint8Array >::value();
  }
  static const char* value(const ::std_srvs::SetUint8ArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetUint8ArrayResponse> should match
// service_traits::DataType< ::std_srvs::SetUint8Array >
template<>
struct DataType< ::std_srvs::SetUint8ArrayResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetUint8Array >::value();
  }
  static const char* value(const ::std_srvs::SetUint8ArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETUINT8ARRAY_H
