// Generated by gencpp from file std_srvs/SetUint32Request.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETUINT32REQUEST_H
#define STD_SRVS_MESSAGE_SETUINT32REQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace std_srvs
{
template <class ContainerAllocator>
struct SetUint32Request_
{
  typedef SetUint32Request_<ContainerAllocator> Type;

  SetUint32Request_()
    : data(0)  {
    }
  SetUint32Request_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef uint32_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::std_srvs::SetUint32Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::std_srvs::SetUint32Request_<ContainerAllocator> const> ConstPtr;

}; // struct SetUint32Request_

typedef ::std_srvs::SetUint32Request_<std::allocator<void> > SetUint32Request;

typedef boost::shared_ptr< ::std_srvs::SetUint32Request > SetUint32RequestPtr;
typedef boost::shared_ptr< ::std_srvs::SetUint32Request const> SetUint32RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::std_srvs::SetUint32Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::std_srvs::SetUint32Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::std_srvs::SetUint32Request_<ContainerAllocator1> & lhs, const ::std_srvs::SetUint32Request_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::std_srvs::SetUint32Request_<ContainerAllocator1> & lhs, const ::std_srvs::SetUint32Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace std_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::std_srvs::SetUint32Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::std_srvs::SetUint32Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_srvs::SetUint32Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_srvs::SetUint32Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_srvs::SetUint32Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_srvs::SetUint32Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::std_srvs::SetUint32Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "304a39449588c7f8ce2df6e8001c5fce";
  }

  static const char* value(const ::std_srvs::SetUint32Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x304a39449588c7f8ULL;
  static const uint64_t static_value2 = 0xce2df6e8001c5fceULL;
};

template<class ContainerAllocator>
struct DataType< ::std_srvs::SetUint32Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_srvs/SetUint32Request";
  }

  static const char* value(const ::std_srvs::SetUint32Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::std_srvs::SetUint32Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 data\n"
;
  }

  static const char* value(const ::std_srvs::SetUint32Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::std_srvs::SetUint32Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetUint32Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::std_srvs::SetUint32Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::std_srvs::SetUint32Request_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETUINT32REQUEST_H
