// Generated by gencpp from file upper_body/arm_moveRequest.msg
// DO NOT EDIT!


#ifndef UPPER_BODY_MESSAGE_ARM_MOVEREQUEST_H
#define UPPER_BODY_MESSAGE_ARM_MOVEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace upper_body
{
template <class ContainerAllocator>
struct arm_moveRequest_
{
  typedef arm_moveRequest_<ContainerAllocator> Type;

  arm_moveRequest_()
    : move_type()
    , left_arm_joints()
    , right_arm_joints()
    , left_arm_pos()
    , right_arm_pos()
    , speed(0.0)  {
      left_arm_pos.assign(0.0);

      right_arm_pos.assign(0.0);
  }
  arm_moveRequest_(const ContainerAllocator& _alloc)
    : move_type(_alloc)
    , left_arm_joints(_alloc)
    , right_arm_joints(_alloc)
    , left_arm_pos()
    , right_arm_pos()
    , speed(0.0)  {
  (void)_alloc;
      left_arm_pos.assign(0.0);

      right_arm_pos.assign(0.0);
  }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _move_type_type;
  _move_type_type move_type;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _left_arm_joints_type;
  _left_arm_joints_type left_arm_joints;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _right_arm_joints_type;
  _right_arm_joints_type right_arm_joints;

   typedef boost::array<float, 7>  _left_arm_pos_type;
  _left_arm_pos_type left_arm_pos;

   typedef boost::array<float, 7>  _right_arm_pos_type;
  _right_arm_pos_type right_arm_pos;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::upper_body::arm_moveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upper_body::arm_moveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct arm_moveRequest_

typedef ::upper_body::arm_moveRequest_<std::allocator<void> > arm_moveRequest;

typedef boost::shared_ptr< ::upper_body::arm_moveRequest > arm_moveRequestPtr;
typedef boost::shared_ptr< ::upper_body::arm_moveRequest const> arm_moveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upper_body::arm_moveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upper_body::arm_moveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::upper_body::arm_moveRequest_<ContainerAllocator1> & lhs, const ::upper_body::arm_moveRequest_<ContainerAllocator2> & rhs)
{
  return lhs.move_type == rhs.move_type &&
    lhs.left_arm_joints == rhs.left_arm_joints &&
    lhs.right_arm_joints == rhs.right_arm_joints &&
    lhs.left_arm_pos == rhs.left_arm_pos &&
    lhs.right_arm_pos == rhs.right_arm_pos &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::upper_body::arm_moveRequest_<ContainerAllocator1> & lhs, const ::upper_body::arm_moveRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace upper_body

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::upper_body::arm_moveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upper_body::arm_moveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upper_body::arm_moveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upper_body::arm_moveRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upper_body::arm_moveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upper_body::arm_moveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upper_body::arm_moveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86d864eb43c1d4b530056a745f746964";
  }

  static const char* value(const ::upper_body::arm_moveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86d864eb43c1d4b5ULL;
  static const uint64_t static_value2 = 0x30056a745f746964ULL;
};

template<class ContainerAllocator>
struct DataType< ::upper_body::arm_moveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upper_body/arm_moveRequest";
  }

  static const char* value(const ::upper_body::arm_moveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upper_body::arm_moveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# motion type\n"
"string move_type # moveJ\\ moveL\\ moveP\\ moveWaistArm\n"
"# moveJ\n"
"float32[] left_arm_joints # unit: rad\n"
"float32[] right_arm_joints # unit: rad\n"
"# moveL\\ moveP\n"
"float32[7] left_arm_pos # [px py pz Qx Qy Qz Qw] unit: m\n"
"float32[7] right_arm_pos # [px py pz Qx Qy Qz Qw] unit: m\n"
"# speed\n"
"float32 speed # unit: rad/s or m/s\n"
;
  }

  static const char* value(const ::upper_body::arm_moveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upper_body::arm_moveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.move_type);
      stream.next(m.left_arm_joints);
      stream.next(m.right_arm_joints);
      stream.next(m.left_arm_pos);
      stream.next(m.right_arm_pos);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arm_moveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upper_body::arm_moveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upper_body::arm_moveRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "move_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.move_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_arm_joints: ";
    if (v.left_arm_joints.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.left_arm_joints.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.left_arm_joints[i]);
    }
    if (v.left_arm_joints.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_arm_joints: ";
    if (v.right_arm_joints.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.right_arm_joints.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.right_arm_joints[i]);
    }
    if (v.right_arm_joints.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_arm_pos: ";
    if (v.left_arm_pos.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.left_arm_pos.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.left_arm_pos[i]);
    }
    if (v.left_arm_pos.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_arm_pos: ";
    if (v.right_arm_pos.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.right_arm_pos.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.right_arm_pos[i]);
    }
    if (v.right_arm_pos.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPPER_BODY_MESSAGE_ARM_MOVEREQUEST_H
