// Generated by gencpp from file upper_body/moveJResponse.msg
// DO NOT EDIT!


#ifndef UPPER_BODY_MESSAGE_MOVEJRESPONSE_H
#define UPPER_BODY_MESSAGE_MOVEJRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace upper_body
{
template <class ContainerAllocator>
struct moveJResponse_
{
  typedef moveJResponse_<ContainerAllocator> Type;

  moveJResponse_()
    : status(0)  {
    }
  moveJResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::upper_body::moveJResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upper_body::moveJResponse_<ContainerAllocator> const> ConstPtr;

}; // struct moveJResponse_

typedef ::upper_body::moveJResponse_<std::allocator<void> > moveJResponse;

typedef boost::shared_ptr< ::upper_body::moveJResponse > moveJResponsePtr;
typedef boost::shared_ptr< ::upper_body::moveJResponse const> moveJResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upper_body::moveJResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upper_body::moveJResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::upper_body::moveJResponse_<ContainerAllocator1> & lhs, const ::upper_body::moveJResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::upper_body::moveJResponse_<ContainerAllocator1> & lhs, const ::upper_body::moveJResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace upper_body

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::upper_body::moveJResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upper_body::moveJResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upper_body::moveJResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upper_body::moveJResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upper_body::moveJResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upper_body::moveJResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upper_body::moveJResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86791dcf1de997ec7de5a0de7e4dcfcc";
  }

  static const char* value(const ::upper_body::moveJResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86791dcf1de997ecULL;
  static const uint64_t static_value2 = 0x7de5a0de7e4dcfccULL;
};

template<class ContainerAllocator>
struct DataType< ::upper_body::moveJResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upper_body/moveJResponse";
  }

  static const char* value(const ::upper_body::moveJResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upper_body::moveJResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 status\n"
"\n"
;
  }

  static const char* value(const ::upper_body::moveJResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upper_body::moveJResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveJResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upper_body::moveJResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upper_body::moveJResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPPER_BODY_MESSAGE_MOVEJRESPONSE_H
