// Generated by gencpp from file upper_body/moveJ.msg
// DO NOT EDIT!


#ifndef UPPER_BODY_MESSAGE_MOVEJ_H
#define UPPER_BODY_MESSAGE_MOVEJ_H

#include <ros/service_traits.h>


#include <upper_body/moveJRequest.h>
#include <upper_body/moveJResponse.h>


namespace upper_body
{

struct moveJ
{

typedef moveJRequest Request;
typedef moveJResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct moveJ
} // namespace upper_body


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::upper_body::moveJ > {
  static const char* value()
  {
    return "2c017c62265b01f61bfb2f0a385a78f9";
  }

  static const char* value(const ::upper_body::moveJ&) { return value(); }
};

template<>
struct DataType< ::upper_body::moveJ > {
  static const char* value()
  {
    return "upper_body/moveJ";
  }

  static const char* value(const ::upper_body::moveJ&) { return value(); }
};


// service_traits::MD5Sum< ::upper_body::moveJRequest> should match
// service_traits::MD5Sum< ::upper_body::moveJ >
template<>
struct MD5Sum< ::upper_body::moveJRequest>
{
  static const char* value()
  {
    return MD5Sum< ::upper_body::moveJ >::value();
  }
  static const char* value(const ::upper_body::moveJRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::upper_body::moveJRequest> should match
// service_traits::DataType< ::upper_body::moveJ >
template<>
struct DataType< ::upper_body::moveJRequest>
{
  static const char* value()
  {
    return DataType< ::upper_body::moveJ >::value();
  }
  static const char* value(const ::upper_body::moveJRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::upper_body::moveJResponse> should match
// service_traits::MD5Sum< ::upper_body::moveJ >
template<>
struct MD5Sum< ::upper_body::moveJResponse>
{
  static const char* value()
  {
    return MD5Sum< ::upper_body::moveJ >::value();
  }
  static const char* value(const ::upper_body::moveJResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::upper_body::moveJResponse> should match
// service_traits::DataType< ::upper_body::moveJ >
template<>
struct DataType< ::upper_body::moveJResponse>
{
  static const char* value()
  {
    return DataType< ::upper_body::moveJ >::value();
  }
  static const char* value(const ::upper_body::moveJResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UPPER_BODY_MESSAGE_MOVEJ_H
