// Generated by gencpp from file upper_body/waist_cmd.msg
// DO NOT EDIT!


#ifndef UPPER_BODY_MESSAGE_WAIST_CMD_H
#define UPPER_BODY_MESSAGE_WAIST_CMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace upper_body
{
template <class ContainerAllocator>
struct waist_cmd_
{
  typedef waist_cmd_<ContainerAllocator> Type;

  waist_cmd_()
    : waistCMD()  {
      waistCMD.assign(0.0);
  }
  waist_cmd_(const ContainerAllocator& _alloc)
    : waistCMD()  {
  (void)_alloc;
      waistCMD.assign(0.0);
  }



   typedef boost::array<float, 3>  _waistCMD_type;
  _waistCMD_type waistCMD;





  typedef boost::shared_ptr< ::upper_body::waist_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upper_body::waist_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct waist_cmd_

typedef ::upper_body::waist_cmd_<std::allocator<void> > waist_cmd;

typedef boost::shared_ptr< ::upper_body::waist_cmd > waist_cmdPtr;
typedef boost::shared_ptr< ::upper_body::waist_cmd const> waist_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upper_body::waist_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upper_body::waist_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::upper_body::waist_cmd_<ContainerAllocator1> & lhs, const ::upper_body::waist_cmd_<ContainerAllocator2> & rhs)
{
  return lhs.waistCMD == rhs.waistCMD;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::upper_body::waist_cmd_<ContainerAllocator1> & lhs, const ::upper_body::waist_cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace upper_body

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::upper_body::waist_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upper_body::waist_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upper_body::waist_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upper_body::waist_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upper_body::waist_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upper_body::waist_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upper_body::waist_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "985c2e8a51e1fd1482af0d011eb5a7d6";
  }

  static const char* value(const ::upper_body::waist_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x985c2e8a51e1fd14ULL;
  static const uint64_t static_value2 = 0x82af0d011eb5a7d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::upper_body::waist_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upper_body/waist_cmd";
  }

  static const char* value(const ::upper_body::waist_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upper_body::waist_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[3] waistCMD # [\"waist_yaw_joint\", \"waist_roll_joint\", \"waist_pitch_joint\"] units: rad\n"
;
  }

  static const char* value(const ::upper_body::waist_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upper_body::waist_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waistCMD);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct waist_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upper_body::waist_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upper_body::waist_cmd_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "waistCMD: ";
    if (v.waistCMD.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.waistCMD.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.waistCMD[i]);
    }
    if (v.waistCMD.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPPER_BODY_MESSAGE_WAIST_CMD_H
