// Generated by gencpp from file limx_arm_msgs/desire_pos.msg
// DO NOT EDIT!


#ifndef LIMX_ARM_MSGS_MESSAGE_DESIRE_POS_H
#define LIMX_ARM_MSGS_MESSAGE_DESIRE_POS_H

#include <ros/service_traits.h>


#include <limx_arm_msgs/desire_posRequest.h>
#include <limx_arm_msgs/desire_posResponse.h>


namespace limx_arm_msgs
{

struct desire_pos
{

typedef desire_posRequest Request;
typedef desire_posResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct desire_pos
} // namespace limx_arm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::limx_arm_msgs::desire_pos > {
  static const char* value()
  {
    return "66df596b0ec651af3f62afa42d52c21b";
  }

  static const char* value(const ::limx_arm_msgs::desire_pos&) { return value(); }
};

template<>
struct DataType< ::limx_arm_msgs::desire_pos > {
  static const char* value()
  {
    return "limx_arm_msgs/desire_pos";
  }

  static const char* value(const ::limx_arm_msgs::desire_pos&) { return value(); }
};


// service_traits::MD5Sum< ::limx_arm_msgs::desire_posRequest> should match
// service_traits::MD5Sum< ::limx_arm_msgs::desire_pos >
template<>
struct MD5Sum< ::limx_arm_msgs::desire_posRequest>
{
  static const char* value()
  {
    return MD5Sum< ::limx_arm_msgs::desire_pos >::value();
  }
  static const char* value(const ::limx_arm_msgs::desire_posRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::limx_arm_msgs::desire_posRequest> should match
// service_traits::DataType< ::limx_arm_msgs::desire_pos >
template<>
struct DataType< ::limx_arm_msgs::desire_posRequest>
{
  static const char* value()
  {
    return DataType< ::limx_arm_msgs::desire_pos >::value();
  }
  static const char* value(const ::limx_arm_msgs::desire_posRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::limx_arm_msgs::desire_posResponse> should match
// service_traits::MD5Sum< ::limx_arm_msgs::desire_pos >
template<>
struct MD5Sum< ::limx_arm_msgs::desire_posResponse>
{
  static const char* value()
  {
    return MD5Sum< ::limx_arm_msgs::desire_pos >::value();
  }
  static const char* value(const ::limx_arm_msgs::desire_posResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::limx_arm_msgs::desire_posResponse> should match
// service_traits::DataType< ::limx_arm_msgs::desire_pos >
template<>
struct DataType< ::limx_arm_msgs::desire_posResponse>
{
  static const char* value()
  {
    return DataType< ::limx_arm_msgs::desire_pos >::value();
  }
  static const char* value(const ::limx_arm_msgs::desire_posResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIMX_ARM_MSGS_MESSAGE_DESIRE_POS_H
