// Generated by gencpp from file limx_arm_msgs/desire_posResponse.msg
// DO NOT EDIT!


#ifndef LIMX_ARM_MSGS_MESSAGE_DESIRE_POSRESPONSE_H
#define LIMX_ARM_MSGS_MESSAGE_DESIRE_POSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace limx_arm_msgs
{
template <class ContainerAllocator>
struct desire_posResponse_
{
  typedef desire_posResponse_<ContainerAllocator> Type;

  desire_posResponse_()
    : status(false)  {
    }
  desire_posResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::limx_arm_msgs::desire_posResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::limx_arm_msgs::desire_posResponse_<ContainerAllocator> const> ConstPtr;

}; // struct desire_posResponse_

typedef ::limx_arm_msgs::desire_posResponse_<std::allocator<void> > desire_posResponse;

typedef boost::shared_ptr< ::limx_arm_msgs::desire_posResponse > desire_posResponsePtr;
typedef boost::shared_ptr< ::limx_arm_msgs::desire_posResponse const> desire_posResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::limx_arm_msgs::desire_posResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::limx_arm_msgs::desire_posResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::limx_arm_msgs::desire_posResponse_<ContainerAllocator1> & lhs, const ::limx_arm_msgs::desire_posResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::limx_arm_msgs::desire_posResponse_<ContainerAllocator1> & lhs, const ::limx_arm_msgs::desire_posResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace limx_arm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::limx_arm_msgs::desire_posResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limx_arm_msgs::desire_posResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::limx_arm_msgs::desire_posResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::limx_arm_msgs::desire_posResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limx_arm_msgs::desire_posResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limx_arm_msgs::desire_posResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::limx_arm_msgs::desire_posResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::limx_arm_msgs::desire_posResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::limx_arm_msgs::desire_posResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "limx_arm_msgs/desire_posResponse";
  }

  static const char* value(const ::limx_arm_msgs::desire_posResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::limx_arm_msgs::desire_posResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"\n"
;
  }

  static const char* value(const ::limx_arm_msgs::desire_posResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::limx_arm_msgs::desire_posResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct desire_posResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::limx_arm_msgs::desire_posResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::limx_arm_msgs::desire_posResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIMX_ARM_MSGS_MESSAGE_DESIRE_POSRESPONSE_H
