// Generated by gencpp from file limx_arm_msgs/gripperResponse.msg
// DO NOT EDIT!


#ifndef LIMX_ARM_MSGS_MESSAGE_GRIPPERRESPONSE_H
#define LIMX_ARM_MSGS_MESSAGE_GRIPPERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace limx_arm_msgs
{
template <class ContainerAllocator>
struct gripperResponse_
{
  typedef gripperResponse_<ContainerAllocator> Type;

  gripperResponse_()
    : status(0)  {
    }
  gripperResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::limx_arm_msgs::gripperResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::limx_arm_msgs::gripperResponse_<ContainerAllocator> const> ConstPtr;

}; // struct gripperResponse_

typedef ::limx_arm_msgs::gripperResponse_<std::allocator<void> > gripperResponse;

typedef boost::shared_ptr< ::limx_arm_msgs::gripperResponse > gripperResponsePtr;
typedef boost::shared_ptr< ::limx_arm_msgs::gripperResponse const> gripperResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::limx_arm_msgs::gripperResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::limx_arm_msgs::gripperResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::limx_arm_msgs::gripperResponse_<ContainerAllocator1> & lhs, const ::limx_arm_msgs::gripperResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::limx_arm_msgs::gripperResponse_<ContainerAllocator1> & lhs, const ::limx_arm_msgs::gripperResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace limx_arm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::limx_arm_msgs::gripperResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limx_arm_msgs::gripperResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::limx_arm_msgs::gripperResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::limx_arm_msgs::gripperResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limx_arm_msgs::gripperResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limx_arm_msgs::gripperResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::limx_arm_msgs::gripperResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86791dcf1de997ec7de5a0de7e4dcfcc";
  }

  static const char* value(const ::limx_arm_msgs::gripperResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86791dcf1de997ecULL;
  static const uint64_t static_value2 = 0x7de5a0de7e4dcfccULL;
};

template<class ContainerAllocator>
struct DataType< ::limx_arm_msgs::gripperResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "limx_arm_msgs/gripperResponse";
  }

  static const char* value(const ::limx_arm_msgs::gripperResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::limx_arm_msgs::gripperResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 status\n"
"\n"
;
  }

  static const char* value(const ::limx_arm_msgs::gripperResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::limx_arm_msgs::gripperResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gripperResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::limx_arm_msgs::gripperResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::limx_arm_msgs::gripperResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIMX_ARM_MSGS_MESSAGE_GRIPPERRESPONSE_H
