# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from teleop_msgs/TeleopRawInput.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class TeleopRawInput(genpy.Message):
  _md5sum = "681b645c832574afd3efcab58e686b87"
  _type = "teleop_msgs/TeleopRawInput"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# 操作者控制器的原始输入量。
# 发送方不解释任何按键含义，组合键语义一律由接收方解释。

# 模拟量，范围 0.0 ~ 1.0
float32 left_trigger
float32 right_trigger
float32 left_grip
float32 right_grip

# 摇杆，[x, y]，范围 -1.0 ~ 1.0
float32[2] left_stick
float32[2] right_stick

# 按键位掩码。预留高位，新增按键不需要改本消息。
uint32 BTN_LEFT_X=1
uint32 BTN_LEFT_Y=2
uint32 BTN_RIGHT_A=4
uint32 BTN_RIGHT_B=8
uint32 BTN_LEFT_STICK=16         # 左摇杆按下
uint32 BTN_RIGHT_STICK=32        # 右摇杆按下
uint32 BTN_LEFT_GRIP=64          # 左 Grip 的布尔态
uint32 BTN_RIGHT_GRIP=128        # 右 Grip 的布尔态
uint32 BTN_LEFT_TRIGGER=256      # 左扳机的布尔态
uint32 BTN_RIGHT_TRIGGER=512     # 右扳机的布尔态
uint32 BTN_LEFT_THUMBREST=1024
uint32 BTN_RIGHT_THUMBREST=2048
uint32 buttons

# 哪些按键位本帧有效。设备不提供的按键，对应位为 0。
# 接收方不得把「设备未提供」当成「按键未按下」。
uint32 buttons_valid
"""
  # Pseudo-constants
  BTN_LEFT_X = 1
  BTN_LEFT_Y = 2
  BTN_RIGHT_A = 4
  BTN_RIGHT_B = 8
  BTN_LEFT_STICK = 16
  BTN_RIGHT_STICK = 32
  BTN_LEFT_GRIP = 64
  BTN_RIGHT_GRIP = 128
  BTN_LEFT_TRIGGER = 256
  BTN_RIGHT_TRIGGER = 512
  BTN_LEFT_THUMBREST = 1024
  BTN_RIGHT_THUMBREST = 2048

  __slots__ = ['left_trigger','right_trigger','left_grip','right_grip','left_stick','right_stick','buttons','buttons_valid']
  _slot_types = ['float32','float32','float32','float32','float32[2]','float32[2]','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_trigger,right_trigger,left_grip,right_grip,left_stick,right_stick,buttons,buttons_valid

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TeleopRawInput, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.left_trigger is None:
        self.left_trigger = 0.
      if self.right_trigger is None:
        self.right_trigger = 0.
      if self.left_grip is None:
        self.left_grip = 0.
      if self.right_grip is None:
        self.right_grip = 0.
      if self.left_stick is None:
        self.left_stick = [0.] * 2
      if self.right_stick is None:
        self.right_stick = [0.] * 2
      if self.buttons is None:
        self.buttons = 0
      if self.buttons_valid is None:
        self.buttons_valid = 0
    else:
      self.left_trigger = 0.
      self.right_trigger = 0.
      self.left_grip = 0.
      self.right_grip = 0.
      self.left_stick = [0.] * 2
      self.right_stick = [0.] * 2
      self.buttons = 0
      self.buttons_valid = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.left_trigger, _x.right_trigger, _x.left_grip, _x.right_grip))
      buff.write(_get_struct_2f().pack(*self.left_stick))
      buff.write(_get_struct_2f().pack(*self.right_stick))
      _x = self
      buff.write(_get_struct_2I().pack(_x.buttons, _x.buttons_valid))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.left_trigger, _x.right_trigger, _x.left_grip, _x.right_grip,) = _get_struct_4f().unpack(str[start:end])
      start = end
      end += 8
      self.left_stick = _get_struct_2f().unpack(str[start:end])
      start = end
      end += 8
      self.right_stick = _get_struct_2f().unpack(str[start:end])
      _x = self
      start = end
      end += 8
      (_x.buttons, _x.buttons_valid,) = _get_struct_2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.left_trigger, _x.right_trigger, _x.left_grip, _x.right_grip))
      buff.write(self.left_stick.tostring())
      buff.write(self.right_stick.tostring())
      _x = self
      buff.write(_get_struct_2I().pack(_x.buttons, _x.buttons_valid))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.left_trigger, _x.right_trigger, _x.left_grip, _x.right_grip,) = _get_struct_4f().unpack(str[start:end])
      start = end
      end += 8
      self.left_stick = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=2)
      start = end
      end += 8
      self.right_stick = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=2)
      _x = self
      start = end
      end += 8
      (_x.buttons, _x.buttons_valid,) = _get_struct_2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
