# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from teleop_msgs/TeleopTarget.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import geometry_msgs.msg

class TeleopTarget(genpy.Message):
  _md5sum = "07cc223d3f4368b67d350d5620e9bced"
  _type = "teleop_msgs/TeleopTarget"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# 遥操作中的单个跟踪目标（末端、头、躯干、足等）。
# 作为 TeleopIntentFrame.targets 的元素使用。

# 目标名。约定值：left_hand / right_hand / head / torso / base /
# left_foot / right_foot / left_wrist / right_wrist。
# 新增跟踪目标只需约定新名字，不需要改本消息。
string name

# 目标位姿。参考系由 TeleopIntentFrame.reference_frame 指定。
geometry_msgs/Pose pose

# 数据可信度。接收方据此决定跟随、降级还是忽略。
uint8 VALIDITY_INVALID=0       # 非法，接收方必须忽略
uint8 VALIDITY_VALID=1         # 新鲜可用
uint8 VALIDITY_STALE=2         # 有数据但已超期
uint8 VALIDITY_EXTRAPOLATED=3  # 由外推得到，非实测
uint8 validity

# 该目标数据的采集时刻。与帧组装时刻（header.stamp）可能不同，
# 接收方据此判断单个目标的新鲜度。
time source_stamp

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  # Pseudo-constants
  VALIDITY_INVALID = 0
  VALIDITY_VALID = 1
  VALIDITY_STALE = 2
  VALIDITY_EXTRAPOLATED = 3

  __slots__ = ['name','pose','validity','source_stamp']
  _slot_types = ['string','geometry_msgs/Pose','uint8','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       name,pose,validity,source_stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TeleopTarget, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.name is None:
        self.name = ''
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.validity is None:
        self.validity = 0
      if self.source_stamp is None:
        self.source_stamp = genpy.Time()
    else:
      self.name = ''
      self.pose = geometry_msgs.msg.Pose()
      self.validity = 0
      self.source_stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7dB2I().pack(_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.validity, _x.source_stamp.secs, _x.source_stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.source_stamp is None:
        self.source_stamp = genpy.Time()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name = str[start:end]
      _x = self
      start = end
      end += 65
      (_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.validity, _x.source_stamp.secs, _x.source_stamp.nsecs,) = _get_struct_7dB2I().unpack(str[start:end])
      self.source_stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7dB2I().pack(_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.validity, _x.source_stamp.secs, _x.source_stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.source_stamp is None:
        self.source_stamp = genpy.Time()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name = str[start:end]
      _x = self
      start = end
      end += 65
      (_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.validity, _x.source_stamp.secs, _x.source_stamp.nsecs,) = _get_struct_7dB2I().unpack(str[start:end])
      self.source_stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7dB2I = None
def _get_struct_7dB2I():
    global _struct_7dB2I
    if _struct_7dB2I is None:
        _struct_7dB2I = struct.Struct("<7dB2I")
    return _struct_7dB2I
