// Generated by gencpp from file upper_body/arm_servo.msg
// DO NOT EDIT!


#ifndef UPPER_BODY_MESSAGE_ARM_SERVO_H
#define UPPER_BODY_MESSAGE_ARM_SERVO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace upper_body
{
template <class ContainerAllocator>
struct arm_servo_
{
  typedef arm_servo_<ContainerAllocator> Type;

  arm_servo_()
    : servo_type()
    , left_arm_joints()
    , right_arm_joints()
    , left_arm_pos()
    , right_arm_pos()  {
      left_arm_pos.assign(0.0);

      right_arm_pos.assign(0.0);
  }
  arm_servo_(const ContainerAllocator& _alloc)
    : servo_type(_alloc)
    , left_arm_joints(_alloc)
    , right_arm_joints(_alloc)
    , left_arm_pos()
    , right_arm_pos()  {
  (void)_alloc;
      left_arm_pos.assign(0.0);

      right_arm_pos.assign(0.0);
  }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _servo_type_type;
  _servo_type_type servo_type;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _left_arm_joints_type;
  _left_arm_joints_type left_arm_joints;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _right_arm_joints_type;
  _right_arm_joints_type right_arm_joints;

   typedef boost::array<float, 7>  _left_arm_pos_type;
  _left_arm_pos_type left_arm_pos;

   typedef boost::array<float, 7>  _right_arm_pos_type;
  _right_arm_pos_type right_arm_pos;





  typedef boost::shared_ptr< ::upper_body::arm_servo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upper_body::arm_servo_<ContainerAllocator> const> ConstPtr;

}; // struct arm_servo_

typedef ::upper_body::arm_servo_<std::allocator<void> > arm_servo;

typedef boost::shared_ptr< ::upper_body::arm_servo > arm_servoPtr;
typedef boost::shared_ptr< ::upper_body::arm_servo const> arm_servoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upper_body::arm_servo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upper_body::arm_servo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::upper_body::arm_servo_<ContainerAllocator1> & lhs, const ::upper_body::arm_servo_<ContainerAllocator2> & rhs)
{
  return lhs.servo_type == rhs.servo_type &&
    lhs.left_arm_joints == rhs.left_arm_joints &&
    lhs.right_arm_joints == rhs.right_arm_joints &&
    lhs.left_arm_pos == rhs.left_arm_pos &&
    lhs.right_arm_pos == rhs.right_arm_pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::upper_body::arm_servo_<ContainerAllocator1> & lhs, const ::upper_body::arm_servo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace upper_body

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::upper_body::arm_servo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upper_body::arm_servo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upper_body::arm_servo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upper_body::arm_servo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upper_body::arm_servo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upper_body::arm_servo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upper_body::arm_servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97e96a0b33437f001f2d5b69b43cfc77";
  }

  static const char* value(const ::upper_body::arm_servo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97e96a0b33437f00ULL;
  static const uint64_t static_value2 = 0x1f2d5b69b43cfc77ULL;
};

template<class ContainerAllocator>
struct DataType< ::upper_body::arm_servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upper_body/arm_servo";
  }

  static const char* value(const ::upper_body::arm_servo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upper_body::arm_servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string servo_type # servoJ or servoP\n"
"# servoJ\n"
"float32[] left_arm_joints # unit: rad\n"
"float32[] right_arm_joints # unit: rad\n"
"# servoP\n"
"float32[7] left_arm_pos # [px py pz Qx Qy Qz Qw] unit: m\n"
"float32[7] right_arm_pos # [px py pz Qx Qy Qz Qw] unit: mz\n"
;
  }

  static const char* value(const ::upper_body::arm_servo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upper_body::arm_servo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servo_type);
      stream.next(m.left_arm_joints);
      stream.next(m.right_arm_joints);
      stream.next(m.left_arm_pos);
      stream.next(m.right_arm_pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arm_servo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upper_body::arm_servo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upper_body::arm_servo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "servo_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.servo_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_arm_joints: ";
    if (v.left_arm_joints.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.left_arm_joints.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.left_arm_joints[i]);
    }
    if (v.left_arm_joints.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_arm_joints: ";
    if (v.right_arm_joints.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.right_arm_joints.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.right_arm_joints[i]);
    }
    if (v.right_arm_joints.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_arm_pos: ";
    if (v.left_arm_pos.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.left_arm_pos.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.left_arm_pos[i]);
    }
    if (v.left_arm_pos.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_arm_pos: ";
    if (v.right_arm_pos.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.right_arm_pos.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.right_arm_pos[i]);
    }
    if (v.right_arm_pos.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPPER_BODY_MESSAGE_ARM_SERVO_H
