// Generated by gencpp from file upper_body/arm_move.msg
// DO NOT EDIT!


#ifndef UPPER_BODY_MESSAGE_ARM_MOVE_H
#define UPPER_BODY_MESSAGE_ARM_MOVE_H

#include <ros/service_traits.h>


#include <upper_body/arm_moveRequest.h>
#include <upper_body/arm_moveResponse.h>


namespace upper_body
{

struct arm_move
{

typedef arm_moveRequest Request;
typedef arm_moveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct arm_move
} // namespace upper_body


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::upper_body::arm_move > {
  static const char* value()
  {
    return "f13b61a0c47c46ffa39677bd176fad6d";
  }

  static const char* value(const ::upper_body::arm_move&) { return value(); }
};

template<>
struct DataType< ::upper_body::arm_move > {
  static const char* value()
  {
    return "upper_body/arm_move";
  }

  static const char* value(const ::upper_body::arm_move&) { return value(); }
};


// service_traits::MD5Sum< ::upper_body::arm_moveRequest> should match
// service_traits::MD5Sum< ::upper_body::arm_move >
template<>
struct MD5Sum< ::upper_body::arm_moveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::upper_body::arm_move >::value();
  }
  static const char* value(const ::upper_body::arm_moveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::upper_body::arm_moveRequest> should match
// service_traits::DataType< ::upper_body::arm_move >
template<>
struct DataType< ::upper_body::arm_moveRequest>
{
  static const char* value()
  {
    return DataType< ::upper_body::arm_move >::value();
  }
  static const char* value(const ::upper_body::arm_moveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::upper_body::arm_moveResponse> should match
// service_traits::MD5Sum< ::upper_body::arm_move >
template<>
struct MD5Sum< ::upper_body::arm_moveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::upper_body::arm_move >::value();
  }
  static const char* value(const ::upper_body::arm_moveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::upper_body::arm_moveResponse> should match
// service_traits::DataType< ::upper_body::arm_move >
template<>
struct DataType< ::upper_body::arm_moveResponse>
{
  static const char* value()
  {
    return DataType< ::upper_body::arm_move >::value();
  }
  static const char* value(const ::upper_body::arm_moveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UPPER_BODY_MESSAGE_ARM_MOVE_H
