// Generated by gencpp from file limx_arm_msgs/desire_posRequest.msg
// DO NOT EDIT!


#ifndef LIMX_ARM_MSGS_MESSAGE_DESIRE_POSREQUEST_H
#define LIMX_ARM_MSGS_MESSAGE_DESIRE_POSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace limx_arm_msgs
{
template <class ContainerAllocator>
struct desire_posRequest_
{
  typedef desire_posRequest_<ContainerAllocator> Type;

  desire_posRequest_()
    : taskNum(0)
    , desire_pos()
    , co_control(false)  {
      desire_pos.assign(0.0);
  }
  desire_posRequest_(const ContainerAllocator& _alloc)
    : taskNum(0)
    , desire_pos()
    , co_control(false)  {
  (void)_alloc;
      desire_pos.assign(0.0);
  }



   typedef int32_t _taskNum_type;
  _taskNum_type taskNum;

   typedef boost::array<float, 6>  _desire_pos_type;
  _desire_pos_type desire_pos;

   typedef uint8_t _co_control_type;
  _co_control_type co_control;





  typedef boost::shared_ptr< ::limx_arm_msgs::desire_posRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::limx_arm_msgs::desire_posRequest_<ContainerAllocator> const> ConstPtr;

}; // struct desire_posRequest_

typedef ::limx_arm_msgs::desire_posRequest_<std::allocator<void> > desire_posRequest;

typedef boost::shared_ptr< ::limx_arm_msgs::desire_posRequest > desire_posRequestPtr;
typedef boost::shared_ptr< ::limx_arm_msgs::desire_posRequest const> desire_posRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::limx_arm_msgs::desire_posRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::limx_arm_msgs::desire_posRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::limx_arm_msgs::desire_posRequest_<ContainerAllocator1> & lhs, const ::limx_arm_msgs::desire_posRequest_<ContainerAllocator2> & rhs)
{
  return lhs.taskNum == rhs.taskNum &&
    lhs.desire_pos == rhs.desire_pos &&
    lhs.co_control == rhs.co_control;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::limx_arm_msgs::desire_posRequest_<ContainerAllocator1> & lhs, const ::limx_arm_msgs::desire_posRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace limx_arm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::limx_arm_msgs::desire_posRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limx_arm_msgs::desire_posRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::limx_arm_msgs::desire_posRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::limx_arm_msgs::desire_posRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limx_arm_msgs::desire_posRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limx_arm_msgs::desire_posRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::limx_arm_msgs::desire_posRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c892bd9edc7017c3aca8dce5899122dc";
  }

  static const char* value(const ::limx_arm_msgs::desire_posRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc892bd9edc7017c3ULL;
  static const uint64_t static_value2 = 0xaca8dce5899122dcULL;
};

template<class ContainerAllocator>
struct DataType< ::limx_arm_msgs::desire_posRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "limx_arm_msgs/desire_posRequest";
  }

  static const char* value(const ::limx_arm_msgs::desire_posRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::limx_arm_msgs::desire_posRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 taskNum\n"
"float32[6] desire_pos  # deg/m\n"
"bool co_control\n"
;
  }

  static const char* value(const ::limx_arm_msgs::desire_posRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::limx_arm_msgs::desire_posRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.taskNum);
      stream.next(m.desire_pos);
      stream.next(m.co_control);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct desire_posRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::limx_arm_msgs::desire_posRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::limx_arm_msgs::desire_posRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "taskNum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.taskNum);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "desire_pos: ";
    if (v.desire_pos.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.desire_pos.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.desire_pos[i]);
    }
    if (v.desire_pos.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "co_control: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.co_control);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIMX_ARM_MSGS_MESSAGE_DESIRE_POSREQUEST_H
