// Generated by gencpp from file limx_arm_msgs/gripper.msg
// DO NOT EDIT!


#ifndef LIMX_ARM_MSGS_MESSAGE_GRIPPER_H
#define LIMX_ARM_MSGS_MESSAGE_GRIPPER_H

#include <ros/service_traits.h>


#include <limx_arm_msgs/gripperRequest.h>
#include <limx_arm_msgs/gripperResponse.h>


namespace limx_arm_msgs
{

struct gripper
{

typedef gripperRequest Request;
typedef gripperResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gripper
} // namespace limx_arm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::limx_arm_msgs::gripper > {
  static const char* value()
  {
    return "0f92630af2d2a713e88b3235d577ea49";
  }

  static const char* value(const ::limx_arm_msgs::gripper&) { return value(); }
};

template<>
struct DataType< ::limx_arm_msgs::gripper > {
  static const char* value()
  {
    return "limx_arm_msgs/gripper";
  }

  static const char* value(const ::limx_arm_msgs::gripper&) { return value(); }
};


// service_traits::MD5Sum< ::limx_arm_msgs::gripperRequest> should match
// service_traits::MD5Sum< ::limx_arm_msgs::gripper >
template<>
struct MD5Sum< ::limx_arm_msgs::gripperRequest>
{
  static const char* value()
  {
    return MD5Sum< ::limx_arm_msgs::gripper >::value();
  }
  static const char* value(const ::limx_arm_msgs::gripperRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::limx_arm_msgs::gripperRequest> should match
// service_traits::DataType< ::limx_arm_msgs::gripper >
template<>
struct DataType< ::limx_arm_msgs::gripperRequest>
{
  static const char* value()
  {
    return DataType< ::limx_arm_msgs::gripper >::value();
  }
  static const char* value(const ::limx_arm_msgs::gripperRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::limx_arm_msgs::gripperResponse> should match
// service_traits::MD5Sum< ::limx_arm_msgs::gripper >
template<>
struct MD5Sum< ::limx_arm_msgs::gripperResponse>
{
  static const char* value()
  {
    return MD5Sum< ::limx_arm_msgs::gripper >::value();
  }
  static const char* value(const ::limx_arm_msgs::gripperResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::limx_arm_msgs::gripperResponse> should match
// service_traits::DataType< ::limx_arm_msgs::gripper >
template<>
struct DataType< ::limx_arm_msgs::gripperResponse>
{
  static const char* value()
  {
    return DataType< ::limx_arm_msgs::gripper >::value();
  }
  static const char* value(const ::limx_arm_msgs::gripperResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIMX_ARM_MSGS_MESSAGE_GRIPPER_H
