// Generated by gencpp from file limx_arm_msgs/motion.msg
// DO NOT EDIT!


#ifndef LIMX_ARM_MSGS_MESSAGE_MOTION_H
#define LIMX_ARM_MSGS_MESSAGE_MOTION_H

#include <ros/service_traits.h>


#include <limx_arm_msgs/motionRequest.h>
#include <limx_arm_msgs/motionResponse.h>


namespace limx_arm_msgs
{

struct motion
{

typedef motionRequest Request;
typedef motionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct motion
} // namespace limx_arm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::limx_arm_msgs::motion > {
  static const char* value()
  {
    return "8f1c1118d46310f55cbaa0a387118cdb";
  }

  static const char* value(const ::limx_arm_msgs::motion&) { return value(); }
};

template<>
struct DataType< ::limx_arm_msgs::motion > {
  static const char* value()
  {
    return "limx_arm_msgs/motion";
  }

  static const char* value(const ::limx_arm_msgs::motion&) { return value(); }
};


// service_traits::MD5Sum< ::limx_arm_msgs::motionRequest> should match
// service_traits::MD5Sum< ::limx_arm_msgs::motion >
template<>
struct MD5Sum< ::limx_arm_msgs::motionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::limx_arm_msgs::motion >::value();
  }
  static const char* value(const ::limx_arm_msgs::motionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::limx_arm_msgs::motionRequest> should match
// service_traits::DataType< ::limx_arm_msgs::motion >
template<>
struct DataType< ::limx_arm_msgs::motionRequest>
{
  static const char* value()
  {
    return DataType< ::limx_arm_msgs::motion >::value();
  }
  static const char* value(const ::limx_arm_msgs::motionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::limx_arm_msgs::motionResponse> should match
// service_traits::MD5Sum< ::limx_arm_msgs::motion >
template<>
struct MD5Sum< ::limx_arm_msgs::motionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::limx_arm_msgs::motion >::value();
  }
  static const char* value(const ::limx_arm_msgs::motionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::limx_arm_msgs::motionResponse> should match
// service_traits::DataType< ::limx_arm_msgs::motion >
template<>
struct DataType< ::limx_arm_msgs::motionResponse>
{
  static const char* value()
  {
    return DataType< ::limx_arm_msgs::motion >::value();
  }
  static const char* value(const ::limx_arm_msgs::motionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIMX_ARM_MSGS_MESSAGE_MOTION_H
