// Generated by gencpp from file teleop_msgs/TeleopRawInput.msg
// DO NOT EDIT!


#ifndef TELEOP_MSGS_MESSAGE_TELEOPRAWINPUT_H
#define TELEOP_MSGS_MESSAGE_TELEOPRAWINPUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace teleop_msgs
{
template <class ContainerAllocator>
struct TeleopRawInput_
{
  typedef TeleopRawInput_<ContainerAllocator> Type;

  TeleopRawInput_()
    : left_trigger(0.0)
    , right_trigger(0.0)
    , left_grip(0.0)
    , right_grip(0.0)
    , left_stick()
    , right_stick()
    , buttons(0)
    , buttons_valid(0)  {
      left_stick.assign(0.0);

      right_stick.assign(0.0);
  }
  TeleopRawInput_(const ContainerAllocator& _alloc)
    : left_trigger(0.0)
    , right_trigger(0.0)
    , left_grip(0.0)
    , right_grip(0.0)
    , left_stick()
    , right_stick()
    , buttons(0)
    , buttons_valid(0)  {
  (void)_alloc;
      left_stick.assign(0.0);

      right_stick.assign(0.0);
  }



   typedef float _left_trigger_type;
  _left_trigger_type left_trigger;

   typedef float _right_trigger_type;
  _right_trigger_type right_trigger;

   typedef float _left_grip_type;
  _left_grip_type left_grip;

   typedef float _right_grip_type;
  _right_grip_type right_grip;

   typedef boost::array<float, 2>  _left_stick_type;
  _left_stick_type left_stick;

   typedef boost::array<float, 2>  _right_stick_type;
  _right_stick_type right_stick;

   typedef uint32_t _buttons_type;
  _buttons_type buttons;

   typedef uint32_t _buttons_valid_type;
  _buttons_valid_type buttons_valid;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(BTN_LEFT_X)
  #undef BTN_LEFT_X
#endif
#if defined(_WIN32) && defined(BTN_LEFT_Y)
  #undef BTN_LEFT_Y
#endif
#if defined(_WIN32) && defined(BTN_RIGHT_A)
  #undef BTN_RIGHT_A
#endif
#if defined(_WIN32) && defined(BTN_RIGHT_B)
  #undef BTN_RIGHT_B
#endif
#if defined(_WIN32) && defined(BTN_LEFT_STICK)
  #undef BTN_LEFT_STICK
#endif
#if defined(_WIN32) && defined(BTN_RIGHT_STICK)
  #undef BTN_RIGHT_STICK
#endif
#if defined(_WIN32) && defined(BTN_LEFT_GRIP)
  #undef BTN_LEFT_GRIP
#endif
#if defined(_WIN32) && defined(BTN_RIGHT_GRIP)
  #undef BTN_RIGHT_GRIP
#endif
#if defined(_WIN32) && defined(BTN_LEFT_TRIGGER)
  #undef BTN_LEFT_TRIGGER
#endif
#if defined(_WIN32) && defined(BTN_RIGHT_TRIGGER)
  #undef BTN_RIGHT_TRIGGER
#endif
#if defined(_WIN32) && defined(BTN_LEFT_THUMBREST)
  #undef BTN_LEFT_THUMBREST
#endif
#if defined(_WIN32) && defined(BTN_RIGHT_THUMBREST)
  #undef BTN_RIGHT_THUMBREST
#endif

  enum {
    BTN_LEFT_X = 1u,
    BTN_LEFT_Y = 2u,
    BTN_RIGHT_A = 4u,
    BTN_RIGHT_B = 8u,
    BTN_LEFT_STICK = 16u,
    BTN_RIGHT_STICK = 32u,
    BTN_LEFT_GRIP = 64u,
    BTN_RIGHT_GRIP = 128u,
    BTN_LEFT_TRIGGER = 256u,
    BTN_RIGHT_TRIGGER = 512u,
    BTN_LEFT_THUMBREST = 1024u,
    BTN_RIGHT_THUMBREST = 2048u,
  };


  typedef boost::shared_ptr< ::teleop_msgs::TeleopRawInput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::teleop_msgs::TeleopRawInput_<ContainerAllocator> const> ConstPtr;

}; // struct TeleopRawInput_

typedef ::teleop_msgs::TeleopRawInput_<std::allocator<void> > TeleopRawInput;

typedef boost::shared_ptr< ::teleop_msgs::TeleopRawInput > TeleopRawInputPtr;
typedef boost::shared_ptr< ::teleop_msgs::TeleopRawInput const> TeleopRawInputConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::teleop_msgs::TeleopRawInput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::teleop_msgs::TeleopRawInput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::teleop_msgs::TeleopRawInput_<ContainerAllocator1> & lhs, const ::teleop_msgs::TeleopRawInput_<ContainerAllocator2> & rhs)
{
  return lhs.left_trigger == rhs.left_trigger &&
    lhs.right_trigger == rhs.right_trigger &&
    lhs.left_grip == rhs.left_grip &&
    lhs.right_grip == rhs.right_grip &&
    lhs.left_stick == rhs.left_stick &&
    lhs.right_stick == rhs.right_stick &&
    lhs.buttons == rhs.buttons &&
    lhs.buttons_valid == rhs.buttons_valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::teleop_msgs::TeleopRawInput_<ContainerAllocator1> & lhs, const ::teleop_msgs::TeleopRawInput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace teleop_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::teleop_msgs::TeleopRawInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teleop_msgs::TeleopRawInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teleop_msgs::TeleopRawInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teleop_msgs::TeleopRawInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teleop_msgs::TeleopRawInput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teleop_msgs::TeleopRawInput_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::teleop_msgs::TeleopRawInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "681b645c832574afd3efcab58e686b87";
  }

  static const char* value(const ::teleop_msgs::TeleopRawInput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x681b645c832574afULL;
  static const uint64_t static_value2 = 0xd3efcab58e686b87ULL;
};

template<class ContainerAllocator>
struct DataType< ::teleop_msgs::TeleopRawInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "teleop_msgs/TeleopRawInput";
  }

  static const char* value(const ::teleop_msgs::TeleopRawInput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::teleop_msgs::TeleopRawInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 操作者控制器的原始输入量。\n"
"# 发送方不解释任何按键含义，组合键语义一律由接收方解释。\n"
"\n"
"# 模拟量，范围 0.0 ~ 1.0\n"
"float32 left_trigger\n"
"float32 right_trigger\n"
"float32 left_grip\n"
"float32 right_grip\n"
"\n"
"# 摇杆，[x, y]，范围 -1.0 ~ 1.0\n"
"float32[2] left_stick\n"
"float32[2] right_stick\n"
"\n"
"# 按键位掩码。预留高位，新增按键不需要改本消息。\n"
"uint32 BTN_LEFT_X=1\n"
"uint32 BTN_LEFT_Y=2\n"
"uint32 BTN_RIGHT_A=4\n"
"uint32 BTN_RIGHT_B=8\n"
"uint32 BTN_LEFT_STICK=16         # 左摇杆按下\n"
"uint32 BTN_RIGHT_STICK=32        # 右摇杆按下\n"
"uint32 BTN_LEFT_GRIP=64          # 左 Grip 的布尔态\n"
"uint32 BTN_RIGHT_GRIP=128        # 右 Grip 的布尔态\n"
"uint32 BTN_LEFT_TRIGGER=256      # 左扳机的布尔态\n"
"uint32 BTN_RIGHT_TRIGGER=512     # 右扳机的布尔态\n"
"uint32 BTN_LEFT_THUMBREST=1024\n"
"uint32 BTN_RIGHT_THUMBREST=2048\n"
"uint32 buttons\n"
"\n"
"# 哪些按键位本帧有效。设备不提供的按键，对应位为 0。\n"
"# 接收方不得把「设备未提供」当成「按键未按下」。\n"
"uint32 buttons_valid\n"
;
  }

  static const char* value(const ::teleop_msgs::TeleopRawInput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::teleop_msgs::TeleopRawInput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_trigger);
      stream.next(m.right_trigger);
      stream.next(m.left_grip);
      stream.next(m.right_grip);
      stream.next(m.left_stick);
      stream.next(m.right_stick);
      stream.next(m.buttons);
      stream.next(m.buttons_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TeleopRawInput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::teleop_msgs::TeleopRawInput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::teleop_msgs::TeleopRawInput_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "left_trigger: ";
    Printer<float>::stream(s, indent + "  ", v.left_trigger);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_trigger: ";
    Printer<float>::stream(s, indent + "  ", v.right_trigger);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_grip: ";
    Printer<float>::stream(s, indent + "  ", v.left_grip);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_grip: ";
    Printer<float>::stream(s, indent + "  ", v.right_grip);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_stick: ";
    if (v.left_stick.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.left_stick.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.left_stick[i]);
    }
    if (v.left_stick.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_stick: ";
    if (v.right_stick.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.right_stick.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.right_stick[i]);
    }
    if (v.right_stick.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "buttons: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.buttons);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "buttons_valid: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.buttons_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TELEOP_MSGS_MESSAGE_TELEOPRAWINPUT_H
