// Generated by gencpp from file teleop_msgs/TeleopSessionState.msg
// DO NOT EDIT!


#ifndef TELEOP_MSGS_MESSAGE_TELEOPSESSIONSTATE_H
#define TELEOP_MSGS_MESSAGE_TELEOPSESSIONSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <teleop_msgs/TeleopLimbState.h>

namespace teleop_msgs
{
template <class ContainerAllocator>
struct TeleopSessionState_
{
  typedef TeleopSessionState_<ContainerAllocator> Type;

  TeleopSessionState_()
    : header()
    , schema_version(0)
    , session_state(0)
    , mode()
    , limbs()
    , reanchor_epoch(0)
    , retarget_required(false)
    , fault_code(0)
    , fault_detail()  {
    }
  TeleopSessionState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , schema_version(0)
    , session_state(0)
    , mode(_alloc)
    , limbs(_alloc)
    , reanchor_epoch(0)
    , retarget_required(false)
    , fault_code(0)
    , fault_detail(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _schema_version_type;
  _schema_version_type schema_version;

   typedef uint8_t _session_state_type;
  _session_state_type session_state;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mode_type;
  _mode_type mode;

   typedef std::vector< ::teleop_msgs::TeleopLimbState_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::teleop_msgs::TeleopLimbState_<ContainerAllocator> >> _limbs_type;
  _limbs_type limbs;

   typedef uint32_t _reanchor_epoch_type;
  _reanchor_epoch_type reanchor_epoch;

   typedef uint8_t _retarget_required_type;
  _retarget_required_type retarget_required;

   typedef uint8_t _fault_code_type;
  _fault_code_type fault_code;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _fault_detail_type;
  _fault_detail_type fault_detail;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SCHEMA_VERSION)
  #undef SCHEMA_VERSION
#endif
#if defined(_WIN32) && defined(SESSION_INACTIVE)
  #undef SESSION_INACTIVE
#endif
#if defined(_WIN32) && defined(SESSION_ACTIVE)
  #undef SESSION_ACTIVE
#endif
#if defined(_WIN32) && defined(SESSION_HOMING)
  #undef SESSION_HOMING
#endif
#if defined(_WIN32) && defined(SESSION_FAULT)
  #undef SESSION_FAULT
#endif
#if defined(_WIN32) && defined(FAULT_NONE)
  #undef FAULT_NONE
#endif
#if defined(_WIN32) && defined(FAULT_INPUT_TIMEOUT)
  #undef FAULT_INPUT_TIMEOUT
#endif
#if defined(_WIN32) && defined(FAULT_TARGET_JUMP)
  #undef FAULT_TARGET_JUMP
#endif
#if defined(_WIN32) && defined(FAULT_OUTPUT)
  #undef FAULT_OUTPUT
#endif
#if defined(_WIN32) && defined(FAULT_INTERNAL)
  #undef FAULT_INTERNAL
#endif

  enum {
    SCHEMA_VERSION = 1u,
    SESSION_INACTIVE = 0u,
    SESSION_ACTIVE = 1u,
    SESSION_HOMING = 2u,
    SESSION_FAULT = 3u,
    FAULT_NONE = 0u,
    FAULT_INPUT_TIMEOUT = 1u,
    FAULT_TARGET_JUMP = 2u,
    FAULT_OUTPUT = 3u,
    FAULT_INTERNAL = 4u,
  };


  typedef boost::shared_ptr< ::teleop_msgs::TeleopSessionState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::teleop_msgs::TeleopSessionState_<ContainerAllocator> const> ConstPtr;

}; // struct TeleopSessionState_

typedef ::teleop_msgs::TeleopSessionState_<std::allocator<void> > TeleopSessionState;

typedef boost::shared_ptr< ::teleop_msgs::TeleopSessionState > TeleopSessionStatePtr;
typedef boost::shared_ptr< ::teleop_msgs::TeleopSessionState const> TeleopSessionStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::teleop_msgs::TeleopSessionState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::teleop_msgs::TeleopSessionState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::teleop_msgs::TeleopSessionState_<ContainerAllocator1> & lhs, const ::teleop_msgs::TeleopSessionState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.schema_version == rhs.schema_version &&
    lhs.session_state == rhs.session_state &&
    lhs.mode == rhs.mode &&
    lhs.limbs == rhs.limbs &&
    lhs.reanchor_epoch == rhs.reanchor_epoch &&
    lhs.retarget_required == rhs.retarget_required &&
    lhs.fault_code == rhs.fault_code &&
    lhs.fault_detail == rhs.fault_detail;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::teleop_msgs::TeleopSessionState_<ContainerAllocator1> & lhs, const ::teleop_msgs::TeleopSessionState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace teleop_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::teleop_msgs::TeleopSessionState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teleop_msgs::TeleopSessionState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teleop_msgs::TeleopSessionState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teleop_msgs::TeleopSessionState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teleop_msgs::TeleopSessionState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teleop_msgs::TeleopSessionState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::teleop_msgs::TeleopSessionState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ebf383eb5a90bcbbd4b9b1366625b009";
  }

  static const char* value(const ::teleop_msgs::TeleopSessionState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xebf383eb5a90bcbbULL;
  static const uint64_t static_value2 = 0xd4b9b1366625b009ULL;
};

template<class ContainerAllocator>
struct DataType< ::teleop_msgs::TeleopSessionState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "teleop_msgs/TeleopSessionState";
  }

  static const char* value(const ::teleop_msgs::TeleopSessionState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::teleop_msgs::TeleopSessionState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 遥操作会话状态。由决策层单向广播，全系统唯一权威，其余模块只读。\n"
"# 接收方不得维护本状态的副本，也不得自行修改跟随状态。\n"
"\n"
"std_msgs/Header header\n"
"\n"
"uint16 SCHEMA_VERSION=1\n"
"uint16 schema_version\n"
"\n"
"uint8 SESSION_INACTIVE=0  # 未进入遥操作\n"
"uint8 SESSION_ACTIVE=1    # 遥操作激活\n"
"uint8 SESSION_HOMING=2    # 回初始姿态流程中，接收方应暂停输出目标\n"
"uint8 SESSION_FAULT=3     # 故障\n"
"uint8 session_state\n"
"\n"
"# 当前遥操作模式名，由产品定义。用字符串以便新增模式不改本消息。\n"
"string mode\n"
"\n"
"# 逐肢体决策。肢体缺席时按不跟随处理。\n"
"teleop_msgs/TeleopLimbState[] limbs\n"
"\n"
"# 重锚计数，单调递增。数值发生变化即要求接收方用当前输入与末端反馈\n"
"# 重新建立锚点。用计数而非布尔边沿，因为收发双方不同频，边沿会丢。\n"
"uint32 reanchor_epoch\n"
"\n"
"# 是否仍需要接收方计算全身重定向。纯性能提示，接收方可以忽略。\n"
"bool retarget_required\n"
"\n"
"uint8 FAULT_NONE=0\n"
"uint8 FAULT_INPUT_TIMEOUT=1  # 上游输入超时\n"
"uint8 FAULT_TARGET_JUMP=2    # 目标跳变被拦截\n"
"uint8 FAULT_OUTPUT=3         # 下发失败\n"
"uint8 FAULT_INTERNAL=4       # 决策层内部错误\n"
"uint8 fault_code\n"
"\n"
"# 故障详情，供日志与诊断使用，不参与控制判定\n"
"string fault_detail\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: teleop_msgs/TeleopLimbState\n"
"# 会话中单个肢体的决策状态。\n"
"# 作为 TeleopSessionState.limbs 的元素使用。\n"
"\n"
"# 肢体名。与 TeleopTarget.name 取值一致。\n"
"string name\n"
"\n"
"# 该肢体本周期是否处于跟随\n"
"bool following\n"
"\n"
"# 该侧末端是否允许无极开合。\n"
"# 门控由发布方负责，扳机行程到开合程度的映射由接收方负责。\n"
"bool ee_closure_enabled\n"
"\n"
"# 该侧末端当前手势索引。\n"
"# 循环切换与持久化由发布方负责，下发对应手势由接收方负责。\n"
"uint8 ee_gesture_index\n"
;
  }

  static const char* value(const ::teleop_msgs::TeleopSessionState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::teleop_msgs::TeleopSessionState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.schema_version);
      stream.next(m.session_state);
      stream.next(m.mode);
      stream.next(m.limbs);
      stream.next(m.reanchor_epoch);
      stream.next(m.retarget_required);
      stream.next(m.fault_code);
      stream.next(m.fault_detail);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TeleopSessionState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::teleop_msgs::TeleopSessionState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::teleop_msgs::TeleopSessionState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "schema_version: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.schema_version);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "session_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.session_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "limbs: ";
    if (v.limbs.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.limbs.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::teleop_msgs::TeleopLimbState_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.limbs[i]);
    }
    if (v.limbs.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reanchor_epoch: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.reanchor_epoch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "retarget_required: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.retarget_required);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fault_code: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fault_code);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fault_detail: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.fault_detail);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TELEOP_MSGS_MESSAGE_TELEOPSESSIONSTATE_H
