(cl:defpackage limx_arm_msgs-srv
  (:use )
  (:export
   "DA_MOTION"
   "<DA_MOTION-REQUEST>"
   "DA_MOTION-REQUEST"
   "<DA_MOTION-RESPONSE>"
   "DA_MOTION-RESPONSE"
   "DESIRE_POS"
   "<DESIRE_POS-REQUEST>"
   "DESIRE_POS-REQUEST"
   "<DESIRE_POS-RESPONSE>"
   "DESIRE_POS-RESPONSE"
   "GRIPPER"
   "<GRIPPER-REQUEST>"
   "GRIPPER-REQUEST"
   "<GRIPPER-RESPONSE>"
   "GRIPPER-RESPONSE"
   "MOTION"
   "<MOTION-REQUEST>"
   "MOTION-REQUEST"
   "<MOTION-RESPONSE>"
   "MOTION-RESPONSE"
  ))

