# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from teleop_msgs/VRState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class VRState(genpy.Message):
  _md5sum = "00c31bc920504fb5ee84c550ff4ee100"
  _type = "teleop_msgs/VRState"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
float32[16] eyePose  # 眼镜位置姿态矩阵 4x4
float32[16] l   # 左手柄姿态矩阵 4x4
float32[16] r   # 右手柄姿态矩阵 4x4

float32[2] leftJS # 左摇杆
float32 leftTrig  # 左扳机
float32 leftGrip  # 左 Grip 键
bool LThU  # 左拇指（布尔值）
bool LTr   # 左扳机（布尔值）
bool LG    # 左 Grip 键（布尔值）
bool X     # X 键
bool Y     # Y 键

float32[2] rightJS  # 右摇杆
float32 rightTrig   # 右扳机
float32 rightGrip   # 右 Grip 键
bool RThU  # 右拇指（布尔值）
bool RTr   # 右扳机（布尔值）
bool RG    # 右 Grip 键（布尔值）
bool A     # A 键
bool B     # B 键

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','eyePose','l','r','leftJS','leftTrig','leftGrip','LThU','LTr','LG','X','Y','rightJS','rightTrig','rightGrip','RThU','RTr','RG','A','B']
  _slot_types = ['std_msgs/Header','float32[16]','float32[16]','float32[16]','float32[2]','float32','float32','bool','bool','bool','bool','bool','float32[2]','float32','float32','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,eyePose,l,r,leftJS,leftTrig,leftGrip,LThU,LTr,LG,X,Y,rightJS,rightTrig,rightGrip,RThU,RTr,RG,A,B

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VRState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.eyePose is None:
        self.eyePose = [0.] * 16
      if self.l is None:
        self.l = [0.] * 16
      if self.r is None:
        self.r = [0.] * 16
      if self.leftJS is None:
        self.leftJS = [0.] * 2
      if self.leftTrig is None:
        self.leftTrig = 0.
      if self.leftGrip is None:
        self.leftGrip = 0.
      if self.LThU is None:
        self.LThU = False
      if self.LTr is None:
        self.LTr = False
      if self.LG is None:
        self.LG = False
      if self.X is None:
        self.X = False
      if self.Y is None:
        self.Y = False
      if self.rightJS is None:
        self.rightJS = [0.] * 2
      if self.rightTrig is None:
        self.rightTrig = 0.
      if self.rightGrip is None:
        self.rightGrip = 0.
      if self.RThU is None:
        self.RThU = False
      if self.RTr is None:
        self.RTr = False
      if self.RG is None:
        self.RG = False
      if self.A is None:
        self.A = False
      if self.B is None:
        self.B = False
    else:
      self.header = std_msgs.msg.Header()
      self.eyePose = [0.] * 16
      self.l = [0.] * 16
      self.r = [0.] * 16
      self.leftJS = [0.] * 2
      self.leftTrig = 0.
      self.leftGrip = 0.
      self.LThU = False
      self.LTr = False
      self.LG = False
      self.X = False
      self.Y = False
      self.rightJS = [0.] * 2
      self.rightTrig = 0.
      self.rightGrip = 0.
      self.RThU = False
      self.RTr = False
      self.RG = False
      self.A = False
      self.B = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(_get_struct_16f().pack(*self.eyePose))
      buff.write(_get_struct_16f().pack(*self.l))
      buff.write(_get_struct_16f().pack(*self.r))
      buff.write(_get_struct_2f().pack(*self.leftJS))
      _x = self
      buff.write(_get_struct_2f5B().pack(_x.leftTrig, _x.leftGrip, _x.LThU, _x.LTr, _x.LG, _x.X, _x.Y))
      buff.write(_get_struct_2f().pack(*self.rightJS))
      _x = self
      buff.write(_get_struct_2f5B().pack(_x.rightTrig, _x.rightGrip, _x.RThU, _x.RTr, _x.RG, _x.A, _x.B))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 64
      self.eyePose = _get_struct_16f().unpack(str[start:end])
      start = end
      end += 64
      self.l = _get_struct_16f().unpack(str[start:end])
      start = end
      end += 64
      self.r = _get_struct_16f().unpack(str[start:end])
      start = end
      end += 8
      self.leftJS = _get_struct_2f().unpack(str[start:end])
      _x = self
      start = end
      end += 13
      (_x.leftTrig, _x.leftGrip, _x.LThU, _x.LTr, _x.LG, _x.X, _x.Y,) = _get_struct_2f5B().unpack(str[start:end])
      self.LThU = bool(self.LThU)
      self.LTr = bool(self.LTr)
      self.LG = bool(self.LG)
      self.X = bool(self.X)
      self.Y = bool(self.Y)
      start = end
      end += 8
      self.rightJS = _get_struct_2f().unpack(str[start:end])
      _x = self
      start = end
      end += 13
      (_x.rightTrig, _x.rightGrip, _x.RThU, _x.RTr, _x.RG, _x.A, _x.B,) = _get_struct_2f5B().unpack(str[start:end])
      self.RThU = bool(self.RThU)
      self.RTr = bool(self.RTr)
      self.RG = bool(self.RG)
      self.A = bool(self.A)
      self.B = bool(self.B)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(self.eyePose.tostring())
      buff.write(self.l.tostring())
      buff.write(self.r.tostring())
      buff.write(self.leftJS.tostring())
      _x = self
      buff.write(_get_struct_2f5B().pack(_x.leftTrig, _x.leftGrip, _x.LThU, _x.LTr, _x.LG, _x.X, _x.Y))
      buff.write(self.rightJS.tostring())
      _x = self
      buff.write(_get_struct_2f5B().pack(_x.rightTrig, _x.rightGrip, _x.RThU, _x.RTr, _x.RG, _x.A, _x.B))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 64
      self.eyePose = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=16)
      start = end
      end += 64
      self.l = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=16)
      start = end
      end += 64
      self.r = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=16)
      start = end
      end += 8
      self.leftJS = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=2)
      _x = self
      start = end
      end += 13
      (_x.leftTrig, _x.leftGrip, _x.LThU, _x.LTr, _x.LG, _x.X, _x.Y,) = _get_struct_2f5B().unpack(str[start:end])
      self.LThU = bool(self.LThU)
      self.LTr = bool(self.LTr)
      self.LG = bool(self.LG)
      self.X = bool(self.X)
      self.Y = bool(self.Y)
      start = end
      end += 8
      self.rightJS = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=2)
      _x = self
      start = end
      end += 13
      (_x.rightTrig, _x.rightGrip, _x.RThU, _x.RTr, _x.RG, _x.A, _x.B,) = _get_struct_2f5B().unpack(str[start:end])
      self.RThU = bool(self.RThU)
      self.RTr = bool(self.RTr)
      self.RG = bool(self.RG)
      self.A = bool(self.A)
      self.B = bool(self.B)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_16f = None
def _get_struct_16f():
    global _struct_16f
    if _struct_16f is None:
        _struct_16f = struct.Struct("<16f")
    return _struct_16f
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_2f5B = None
def _get_struct_2f5B():
    global _struct_2f5B
    if _struct_2f5B is None:
        _struct_2f5B = struct.Struct("<2f5B")
    return _struct_2f5B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
