(cl:in-package teleop_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          EYEPOSE-VAL
          EYEPOSE
          L-VAL
          L
          R-VAL
          R
          LEFTJS-VAL
          LEFTJS
          LEFTTRIG-VAL
          LEFTTRIG
          LEFTGRIP-VAL
          LEFTGRIP
          LTHU-VAL
          LTHU
          LTR-VAL
          LTR
          LG-VAL
          LG
          X-VAL
          X
          Y-VAL
          Y
          RIGHTJS-VAL
          RIGHTJS
          RIGHTTRIG-VAL
          RIGHTTRIG
          RIGHTGRIP-VAL
          RIGHTGRIP
          RTHU-VAL
          RTHU
          RTR-VAL
          RTR
          RG-VAL
          RG
          A-VAL
          A
          B-VAL
          B
))