// Generated by gencpp from file std_srvs/GetBool.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_GETBOOL_H
#define STD_SRVS_MESSAGE_GETBOOL_H

#include <ros/service_traits.h>


#include <std_srvs/GetBoolRequest.h>
#include <std_srvs/GetBoolResponse.h>


namespace std_srvs
{

struct GetBool
{

typedef GetBoolRequest Request;
typedef GetBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBool
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::GetBool > {
  static const char* value()
  {
    return "43f76a855b16e988566e147b692f2fab";
  }

  static const char* value(const ::std_srvs::GetBool&) { return value(); }
};

template<>
struct DataType< ::std_srvs::GetBool > {
  static const char* value()
  {
    return "std_srvs/GetBool";
  }

  static const char* value(const ::std_srvs::GetBool&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::GetBoolRequest> should match
// service_traits::MD5Sum< ::std_srvs::GetBool >
template<>
struct MD5Sum< ::std_srvs::GetBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetBool >::value();
  }
  static const char* value(const ::std_srvs::GetBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetBoolRequest> should match
// service_traits::DataType< ::std_srvs::GetBool >
template<>
struct DataType< ::std_srvs::GetBoolRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetBool >::value();
  }
  static const char* value(const ::std_srvs::GetBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::GetBoolResponse> should match
// service_traits::MD5Sum< ::std_srvs::GetBool >
template<>
struct MD5Sum< ::std_srvs::GetBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetBool >::value();
  }
  static const char* value(const ::std_srvs::GetBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetBoolResponse> should match
// service_traits::DataType< ::std_srvs::GetBool >
template<>
struct DataType< ::std_srvs::GetBoolResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetBool >::value();
  }
  static const char* value(const ::std_srvs::GetBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_GETBOOL_H
