// Generated by gencpp from file std_srvs/GetFloat64.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_GETFLOAT64_H
#define STD_SRVS_MESSAGE_GETFLOAT64_H

#include <ros/service_traits.h>


#include <std_srvs/GetFloat64Request.h>
#include <std_srvs/GetFloat64Response.h>


namespace std_srvs
{

struct GetFloat64
{

typedef GetFloat64Request Request;
typedef GetFloat64Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFloat64
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::GetFloat64 > {
  static const char* value()
  {
    return "438b39d7999aa4b25db9b49336da31bd";
  }

  static const char* value(const ::std_srvs::GetFloat64&) { return value(); }
};

template<>
struct DataType< ::std_srvs::GetFloat64 > {
  static const char* value()
  {
    return "std_srvs/GetFloat64";
  }

  static const char* value(const ::std_srvs::GetFloat64&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::GetFloat64Request> should match
// service_traits::MD5Sum< ::std_srvs::GetFloat64 >
template<>
struct MD5Sum< ::std_srvs::GetFloat64Request>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetFloat64 >::value();
  }
  static const char* value(const ::std_srvs::GetFloat64Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetFloat64Request> should match
// service_traits::DataType< ::std_srvs::GetFloat64 >
template<>
struct DataType< ::std_srvs::GetFloat64Request>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetFloat64 >::value();
  }
  static const char* value(const ::std_srvs::GetFloat64Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::GetFloat64Response> should match
// service_traits::MD5Sum< ::std_srvs::GetFloat64 >
template<>
struct MD5Sum< ::std_srvs::GetFloat64Response>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetFloat64 >::value();
  }
  static const char* value(const ::std_srvs::GetFloat64Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetFloat64Response> should match
// service_traits::DataType< ::std_srvs::GetFloat64 >
template<>
struct DataType< ::std_srvs::GetFloat64Response>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetFloat64 >::value();
  }
  static const char* value(const ::std_srvs::GetFloat64Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_GETFLOAT64_H
