// Generated by gencpp from file std_srvs/GetFloat32.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_GETFLOAT32_H
#define STD_SRVS_MESSAGE_GETFLOAT32_H

#include <ros/service_traits.h>


#include <std_srvs/GetFloat32Request.h>
#include <std_srvs/GetFloat32Response.h>


namespace std_srvs
{

struct GetFloat32
{

typedef GetFloat32Request Request;
typedef GetFloat32Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFloat32
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::GetFloat32 > {
  static const char* value()
  {
    return "5ef892a71f7c5681b5759df4f5cd6c53";
  }

  static const char* value(const ::std_srvs::GetFloat32&) { return value(); }
};

template<>
struct DataType< ::std_srvs::GetFloat32 > {
  static const char* value()
  {
    return "std_srvs/GetFloat32";
  }

  static const char* value(const ::std_srvs::GetFloat32&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::GetFloat32Request> should match
// service_traits::MD5Sum< ::std_srvs::GetFloat32 >
template<>
struct MD5Sum< ::std_srvs::GetFloat32Request>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetFloat32 >::value();
  }
  static const char* value(const ::std_srvs::GetFloat32Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetFloat32Request> should match
// service_traits::DataType< ::std_srvs::GetFloat32 >
template<>
struct DataType< ::std_srvs::GetFloat32Request>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetFloat32 >::value();
  }
  static const char* value(const ::std_srvs::GetFloat32Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::GetFloat32Response> should match
// service_traits::MD5Sum< ::std_srvs::GetFloat32 >
template<>
struct MD5Sum< ::std_srvs::GetFloat32Response>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetFloat32 >::value();
  }
  static const char* value(const ::std_srvs::GetFloat32Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetFloat32Response> should match
// service_traits::DataType< ::std_srvs::GetFloat32 >
template<>
struct DataType< ::std_srvs::GetFloat32Response>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetFloat32 >::value();
  }
  static const char* value(const ::std_srvs::GetFloat32Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_GETFLOAT32_H
