// Generated by gencpp from file std_srvs/GetInt32WithTitle.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_GETINT32WITHTITLE_H
#define STD_SRVS_MESSAGE_GETINT32WITHTITLE_H

#include <ros/service_traits.h>


#include <std_srvs/GetInt32WithTitleRequest.h>
#include <std_srvs/GetInt32WithTitleResponse.h>


namespace std_srvs
{

struct GetInt32WithTitle
{

typedef GetInt32WithTitleRequest Request;
typedef GetInt32WithTitleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInt32WithTitle
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::GetInt32WithTitle > {
  static const char* value()
  {
    return "31e05a55d1e7a09b0783d26061d41e10";
  }

  static const char* value(const ::std_srvs::GetInt32WithTitle&) { return value(); }
};

template<>
struct DataType< ::std_srvs::GetInt32WithTitle > {
  static const char* value()
  {
    return "std_srvs/GetInt32WithTitle";
  }

  static const char* value(const ::std_srvs::GetInt32WithTitle&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::GetInt32WithTitleRequest> should match
// service_traits::MD5Sum< ::std_srvs::GetInt32WithTitle >
template<>
struct MD5Sum< ::std_srvs::GetInt32WithTitleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetInt32WithTitle >::value();
  }
  static const char* value(const ::std_srvs::GetInt32WithTitleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetInt32WithTitleRequest> should match
// service_traits::DataType< ::std_srvs::GetInt32WithTitle >
template<>
struct DataType< ::std_srvs::GetInt32WithTitleRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetInt32WithTitle >::value();
  }
  static const char* value(const ::std_srvs::GetInt32WithTitleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::GetInt32WithTitleResponse> should match
// service_traits::MD5Sum< ::std_srvs::GetInt32WithTitle >
template<>
struct MD5Sum< ::std_srvs::GetInt32WithTitleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetInt32WithTitle >::value();
  }
  static const char* value(const ::std_srvs::GetInt32WithTitleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetInt32WithTitleResponse> should match
// service_traits::DataType< ::std_srvs::GetInt32WithTitle >
template<>
struct DataType< ::std_srvs::GetInt32WithTitleResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetInt32WithTitle >::value();
  }
  static const char* value(const ::std_srvs::GetInt32WithTitleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_GETINT32WITHTITLE_H
