// Generated by gencpp from file std_srvs/GetStringWithTitle.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_GETSTRINGWITHTITLE_H
#define STD_SRVS_MESSAGE_GETSTRINGWITHTITLE_H

#include <ros/service_traits.h>


#include <std_srvs/GetStringWithTitleRequest.h>
#include <std_srvs/GetStringWithTitleResponse.h>


namespace std_srvs
{

struct GetStringWithTitle
{

typedef GetStringWithTitleRequest Request;
typedef GetStringWithTitleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetStringWithTitle
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::GetStringWithTitle > {
  static const char* value()
  {
    return "810c8c2635a677ff04ec479f60a543bd";
  }

  static const char* value(const ::std_srvs::GetStringWithTitle&) { return value(); }
};

template<>
struct DataType< ::std_srvs::GetStringWithTitle > {
  static const char* value()
  {
    return "std_srvs/GetStringWithTitle";
  }

  static const char* value(const ::std_srvs::GetStringWithTitle&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::GetStringWithTitleRequest> should match
// service_traits::MD5Sum< ::std_srvs::GetStringWithTitle >
template<>
struct MD5Sum< ::std_srvs::GetStringWithTitleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetStringWithTitle >::value();
  }
  static const char* value(const ::std_srvs::GetStringWithTitleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetStringWithTitleRequest> should match
// service_traits::DataType< ::std_srvs::GetStringWithTitle >
template<>
struct DataType< ::std_srvs::GetStringWithTitleRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetStringWithTitle >::value();
  }
  static const char* value(const ::std_srvs::GetStringWithTitleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::GetStringWithTitleResponse> should match
// service_traits::MD5Sum< ::std_srvs::GetStringWithTitle >
template<>
struct MD5Sum< ::std_srvs::GetStringWithTitleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetStringWithTitle >::value();
  }
  static const char* value(const ::std_srvs::GetStringWithTitleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetStringWithTitleResponse> should match
// service_traits::DataType< ::std_srvs::GetStringWithTitle >
template<>
struct DataType< ::std_srvs::GetStringWithTitleResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetStringWithTitle >::value();
  }
  static const char* value(const ::std_srvs::GetStringWithTitleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_GETSTRINGWITHTITLE_H
