// Generated by gencpp from file std_srvs/GetUint32ArrayWithTitleRequest.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_GETUINT32ARRAYWITHTITLEREQUEST_H
#define STD_SRVS_MESSAGE_GETUINT32ARRAYWITHTITLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace std_srvs
{
template <class ContainerAllocator>
struct GetUint32ArrayWithTitleRequest_
{
  typedef GetUint32ArrayWithTitleRequest_<ContainerAllocator> Type;

  GetUint32ArrayWithTitleRequest_()
    : title()  {
    }
  GetUint32ArrayWithTitleRequest_(const ContainerAllocator& _alloc)
    : title(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _title_type;
  _title_type title;





  typedef boost::shared_ptr< ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetUint32ArrayWithTitleRequest_

typedef ::std_srvs::GetUint32ArrayWithTitleRequest_<std::allocator<void> > GetUint32ArrayWithTitleRequest;

typedef boost::shared_ptr< ::std_srvs::GetUint32ArrayWithTitleRequest > GetUint32ArrayWithTitleRequestPtr;
typedef boost::shared_ptr< ::std_srvs::GetUint32ArrayWithTitleRequest const> GetUint32ArrayWithTitleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator1> & lhs, const ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.title == rhs.title;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator1> & lhs, const ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace std_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "148093883cfa9690063ee8ef0e24d755";
  }

  static const char* value(const ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x148093883cfa9690ULL;
  static const uint64_t static_value2 = 0x063ee8ef0e24d755ULL;
};

template<class ContainerAllocator>
struct DataType< ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_srvs/GetUint32ArrayWithTitleRequest";
  }

  static const char* value(const ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string title\n"
;
  }

  static const char* value(const ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.title);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetUint32ArrayWithTitleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::std_srvs::GetUint32ArrayWithTitleRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "title: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.title);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STD_SRVS_MESSAGE_GETUINT32ARRAYWITHTITLEREQUEST_H
