// Generated by gencpp from file std_srvs/GetUint8Array.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_GETUINT8ARRAY_H
#define STD_SRVS_MESSAGE_GETUINT8ARRAY_H

#include <ros/service_traits.h>


#include <std_srvs/GetUint8ArrayRequest.h>
#include <std_srvs/GetUint8ArrayResponse.h>


namespace std_srvs
{

struct GetUint8Array
{

typedef GetUint8ArrayRequest Request;
typedef GetUint8ArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetUint8Array
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::GetUint8Array > {
  static const char* value()
  {
    return "84297f3433ca7dc93f41bd4407c6a4c4";
  }

  static const char* value(const ::std_srvs::GetUint8Array&) { return value(); }
};

template<>
struct DataType< ::std_srvs::GetUint8Array > {
  static const char* value()
  {
    return "std_srvs/GetUint8Array";
  }

  static const char* value(const ::std_srvs::GetUint8Array&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::GetUint8ArrayRequest> should match
// service_traits::MD5Sum< ::std_srvs::GetUint8Array >
template<>
struct MD5Sum< ::std_srvs::GetUint8ArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetUint8Array >::value();
  }
  static const char* value(const ::std_srvs::GetUint8ArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetUint8ArrayRequest> should match
// service_traits::DataType< ::std_srvs::GetUint8Array >
template<>
struct DataType< ::std_srvs::GetUint8ArrayRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetUint8Array >::value();
  }
  static const char* value(const ::std_srvs::GetUint8ArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::GetUint8ArrayResponse> should match
// service_traits::MD5Sum< ::std_srvs::GetUint8Array >
template<>
struct MD5Sum< ::std_srvs::GetUint8ArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::GetUint8Array >::value();
  }
  static const char* value(const ::std_srvs::GetUint8ArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::GetUint8ArrayResponse> should match
// service_traits::DataType< ::std_srvs::GetUint8Array >
template<>
struct DataType< ::std_srvs::GetUint8ArrayResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::GetUint8Array >::value();
  }
  static const char* value(const ::std_srvs::GetUint8ArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_GETUINT8ARRAY_H
