// Generated by gencpp from file std_srvs/GetUint32ArrayWithTitleResponse.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_GETUINT32ARRAYWITHTITLERESPONSE_H
#define STD_SRVS_MESSAGE_GETUINT32ARRAYWITHTITLERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace std_srvs
{
template <class ContainerAllocator>
struct GetUint32ArrayWithTitleResponse_
{
  typedef GetUint32ArrayWithTitleResponse_<ContainerAllocator> Type;

  GetUint32ArrayWithTitleResponse_()
    : data()
    , success(false)
    , message()  {
    }
  GetUint32ArrayWithTitleResponse_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _data_type;
  _data_type data;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetUint32ArrayWithTitleResponse_

typedef ::std_srvs::GetUint32ArrayWithTitleResponse_<std::allocator<void> > GetUint32ArrayWithTitleResponse;

typedef boost::shared_ptr< ::std_srvs::GetUint32ArrayWithTitleResponse > GetUint32ArrayWithTitleResponsePtr;
typedef boost::shared_ptr< ::std_srvs::GetUint32ArrayWithTitleResponse const> GetUint32ArrayWithTitleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator1> & lhs, const ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator1> & lhs, const ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace std_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64a7289ff26fd15c6086810950c31b58";
  }

  static const char* value(const ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64a7289ff26fd15cULL;
  static const uint64_t static_value2 = 0x6086810950c31b58ULL;
};

template<class ContainerAllocator>
struct DataType< ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_srvs/GetUint32ArrayWithTitleResponse";
  }

  static const char* value(const ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32[]  data    # array of data\n"
"bool success   # indicate successful run of triggered service\n"
"string message # informational, e.g. for error messages\n"
;
  }

  static const char* value(const ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetUint32ArrayWithTitleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::std_srvs::GetUint32ArrayWithTitleResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint32_t>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STD_SRVS_MESSAGE_GETUINT32ARRAYWITHTITLERESPONSE_H
