// Generated by gencpp from file std_srvs/SetBoolWithTitle.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETBOOLWITHTITLE_H
#define STD_SRVS_MESSAGE_SETBOOLWITHTITLE_H

#include <ros/service_traits.h>


#include <std_srvs/SetBoolWithTitleRequest.h>
#include <std_srvs/SetBoolWithTitleResponse.h>


namespace std_srvs
{

struct SetBoolWithTitle
{

typedef SetBoolWithTitleRequest Request;
typedef SetBoolWithTitleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBoolWithTitle
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::SetBoolWithTitle > {
  static const char* value()
  {
    return "13c1605af28e84338a7c682325a34ac2";
  }

  static const char* value(const ::std_srvs::SetBoolWithTitle&) { return value(); }
};

template<>
struct DataType< ::std_srvs::SetBoolWithTitle > {
  static const char* value()
  {
    return "std_srvs/SetBoolWithTitle";
  }

  static const char* value(const ::std_srvs::SetBoolWithTitle&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::SetBoolWithTitleRequest> should match
// service_traits::MD5Sum< ::std_srvs::SetBoolWithTitle >
template<>
struct MD5Sum< ::std_srvs::SetBoolWithTitleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetBoolWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetBoolWithTitleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetBoolWithTitleRequest> should match
// service_traits::DataType< ::std_srvs::SetBoolWithTitle >
template<>
struct DataType< ::std_srvs::SetBoolWithTitleRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetBoolWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetBoolWithTitleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::SetBoolWithTitleResponse> should match
// service_traits::MD5Sum< ::std_srvs::SetBoolWithTitle >
template<>
struct MD5Sum< ::std_srvs::SetBoolWithTitleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetBoolWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetBoolWithTitleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetBoolWithTitleResponse> should match
// service_traits::DataType< ::std_srvs::SetBoolWithTitle >
template<>
struct DataType< ::std_srvs::SetBoolWithTitleResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetBoolWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetBoolWithTitleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETBOOLWITHTITLE_H
