// Generated by gencpp from file std_srvs/SetFloat32ArrayWithTitle.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETFLOAT32ARRAYWITHTITLE_H
#define STD_SRVS_MESSAGE_SETFLOAT32ARRAYWITHTITLE_H

#include <ros/service_traits.h>


#include <std_srvs/SetFloat32ArrayWithTitleRequest.h>
#include <std_srvs/SetFloat32ArrayWithTitleResponse.h>


namespace std_srvs
{

struct SetFloat32ArrayWithTitle
{

typedef SetFloat32ArrayWithTitleRequest Request;
typedef SetFloat32ArrayWithTitleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloat32ArrayWithTitle
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::SetFloat32ArrayWithTitle > {
  static const char* value()
  {
    return "64281782d45fe82ff040ed17d40cd2bd";
  }

  static const char* value(const ::std_srvs::SetFloat32ArrayWithTitle&) { return value(); }
};

template<>
struct DataType< ::std_srvs::SetFloat32ArrayWithTitle > {
  static const char* value()
  {
    return "std_srvs/SetFloat32ArrayWithTitle";
  }

  static const char* value(const ::std_srvs::SetFloat32ArrayWithTitle&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::SetFloat32ArrayWithTitleRequest> should match
// service_traits::MD5Sum< ::std_srvs::SetFloat32ArrayWithTitle >
template<>
struct MD5Sum< ::std_srvs::SetFloat32ArrayWithTitleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetFloat32ArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetFloat32ArrayWithTitleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetFloat32ArrayWithTitleRequest> should match
// service_traits::DataType< ::std_srvs::SetFloat32ArrayWithTitle >
template<>
struct DataType< ::std_srvs::SetFloat32ArrayWithTitleRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetFloat32ArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetFloat32ArrayWithTitleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::SetFloat32ArrayWithTitleResponse> should match
// service_traits::MD5Sum< ::std_srvs::SetFloat32ArrayWithTitle >
template<>
struct MD5Sum< ::std_srvs::SetFloat32ArrayWithTitleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetFloat32ArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetFloat32ArrayWithTitleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetFloat32ArrayWithTitleResponse> should match
// service_traits::DataType< ::std_srvs::SetFloat32ArrayWithTitle >
template<>
struct DataType< ::std_srvs::SetFloat32ArrayWithTitleResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetFloat32ArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetFloat32ArrayWithTitleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETFLOAT32ARRAYWITHTITLE_H
