// Generated by gencpp from file std_srvs/SetInt32.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETINT32_H
#define STD_SRVS_MESSAGE_SETINT32_H

#include <ros/service_traits.h>


#include <std_srvs/SetInt32Request.h>
#include <std_srvs/SetInt32Response.h>


namespace std_srvs
{

struct SetInt32
{

typedef SetInt32Request Request;
typedef SetInt32Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInt32
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::SetInt32 > {
  static const char* value()
  {
    return "41a6318c88ca9d75d7a585e2aa4ca6ea";
  }

  static const char* value(const ::std_srvs::SetInt32&) { return value(); }
};

template<>
struct DataType< ::std_srvs::SetInt32 > {
  static const char* value()
  {
    return "std_srvs/SetInt32";
  }

  static const char* value(const ::std_srvs::SetInt32&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::SetInt32Request> should match
// service_traits::MD5Sum< ::std_srvs::SetInt32 >
template<>
struct MD5Sum< ::std_srvs::SetInt32Request>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetInt32 >::value();
  }
  static const char* value(const ::std_srvs::SetInt32Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetInt32Request> should match
// service_traits::DataType< ::std_srvs::SetInt32 >
template<>
struct DataType< ::std_srvs::SetInt32Request>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetInt32 >::value();
  }
  static const char* value(const ::std_srvs::SetInt32Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::SetInt32Response> should match
// service_traits::MD5Sum< ::std_srvs::SetInt32 >
template<>
struct MD5Sum< ::std_srvs::SetInt32Response>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetInt32 >::value();
  }
  static const char* value(const ::std_srvs::SetInt32Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetInt32Response> should match
// service_traits::DataType< ::std_srvs::SetInt32 >
template<>
struct DataType< ::std_srvs::SetInt32Response>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetInt32 >::value();
  }
  static const char* value(const ::std_srvs::SetInt32Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETINT32_H
