// Generated by gencpp from file std_srvs/SetInt32ArrayRequest.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETINT32ARRAYREQUEST_H
#define STD_SRVS_MESSAGE_SETINT32ARRAYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace std_srvs
{
template <class ContainerAllocator>
struct SetInt32ArrayRequest_
{
  typedef SetInt32ArrayRequest_<ContainerAllocator> Type;

  SetInt32ArrayRequest_()
    : data()  {
    }
  SetInt32ArrayRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetInt32ArrayRequest_

typedef ::std_srvs::SetInt32ArrayRequest_<std::allocator<void> > SetInt32ArrayRequest;

typedef boost::shared_ptr< ::std_srvs::SetInt32ArrayRequest > SetInt32ArrayRequestPtr;
typedef boost::shared_ptr< ::std_srvs::SetInt32ArrayRequest const> SetInt32ArrayRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator1> & lhs, const ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator1> & lhs, const ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace std_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "563b27884d008b0d2adff54dc1f9e4f5";
  }

  static const char* value(const ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x563b27884d008b0dULL;
  static const uint64_t static_value2 = 0x2adff54dc1f9e4f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_srvs/SetInt32ArrayRequest";
  }

  static const char* value(const ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[]  data    # array of data\n"
;
  }

  static const char* value(const ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetInt32ArrayRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::std_srvs::SetInt32ArrayRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETINT32ARRAYREQUEST_H
