// Generated by gencpp from file std_srvs/SetStringArrayWithTitle.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETSTRINGARRAYWITHTITLE_H
#define STD_SRVS_MESSAGE_SETSTRINGARRAYWITHTITLE_H

#include <ros/service_traits.h>


#include <std_srvs/SetStringArrayWithTitleRequest.h>
#include <std_srvs/SetStringArrayWithTitleResponse.h>


namespace std_srvs
{

struct SetStringArrayWithTitle
{

typedef SetStringArrayWithTitleRequest Request;
typedef SetStringArrayWithTitleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetStringArrayWithTitle
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::SetStringArrayWithTitle > {
  static const char* value()
  {
    return "f7337e803bf7ae13f1248c6c48b226a8";
  }

  static const char* value(const ::std_srvs::SetStringArrayWithTitle&) { return value(); }
};

template<>
struct DataType< ::std_srvs::SetStringArrayWithTitle > {
  static const char* value()
  {
    return "std_srvs/SetStringArrayWithTitle";
  }

  static const char* value(const ::std_srvs::SetStringArrayWithTitle&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::SetStringArrayWithTitleRequest> should match
// service_traits::MD5Sum< ::std_srvs::SetStringArrayWithTitle >
template<>
struct MD5Sum< ::std_srvs::SetStringArrayWithTitleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetStringArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetStringArrayWithTitleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetStringArrayWithTitleRequest> should match
// service_traits::DataType< ::std_srvs::SetStringArrayWithTitle >
template<>
struct DataType< ::std_srvs::SetStringArrayWithTitleRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetStringArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetStringArrayWithTitleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::SetStringArrayWithTitleResponse> should match
// service_traits::MD5Sum< ::std_srvs::SetStringArrayWithTitle >
template<>
struct MD5Sum< ::std_srvs::SetStringArrayWithTitleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetStringArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetStringArrayWithTitleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetStringArrayWithTitleResponse> should match
// service_traits::DataType< ::std_srvs::SetStringArrayWithTitle >
template<>
struct DataType< ::std_srvs::SetStringArrayWithTitleResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetStringArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetStringArrayWithTitleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETSTRINGARRAYWITHTITLE_H
