// Generated by gencpp from file std_srvs/SetString.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETSTRING_H
#define STD_SRVS_MESSAGE_SETSTRING_H

#include <ros/service_traits.h>


#include <std_srvs/SetStringRequest.h>
#include <std_srvs/SetStringResponse.h>


namespace std_srvs
{

struct SetString
{

typedef SetStringRequest Request;
typedef SetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetString
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::SetString > {
  static const char* value()
  {
    return "546971982e3fbbd5a41e60fb6432e357";
  }

  static const char* value(const ::std_srvs::SetString&) { return value(); }
};

template<>
struct DataType< ::std_srvs::SetString > {
  static const char* value()
  {
    return "std_srvs/SetString";
  }

  static const char* value(const ::std_srvs::SetString&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::SetStringRequest> should match
// service_traits::MD5Sum< ::std_srvs::SetString >
template<>
struct MD5Sum< ::std_srvs::SetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetString >::value();
  }
  static const char* value(const ::std_srvs::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetStringRequest> should match
// service_traits::DataType< ::std_srvs::SetString >
template<>
struct DataType< ::std_srvs::SetStringRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetString >::value();
  }
  static const char* value(const ::std_srvs::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::SetStringResponse> should match
// service_traits::MD5Sum< ::std_srvs::SetString >
template<>
struct MD5Sum< ::std_srvs::SetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetString >::value();
  }
  static const char* value(const ::std_srvs::SetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetStringResponse> should match
// service_traits::DataType< ::std_srvs::SetString >
template<>
struct DataType< ::std_srvs::SetStringResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetString >::value();
  }
  static const char* value(const ::std_srvs::SetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETSTRING_H
