// Generated by gencpp from file std_srvs/SetUint32.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETUINT32_H
#define STD_SRVS_MESSAGE_SETUINT32_H

#include <ros/service_traits.h>


#include <std_srvs/SetUint32Request.h>
#include <std_srvs/SetUint32Response.h>


namespace std_srvs
{

struct SetUint32
{

typedef SetUint32Request Request;
typedef SetUint32Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetUint32
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::SetUint32 > {
  static const char* value()
  {
    return "0f2f397ed73410a6aa0c7229afbae23d";
  }

  static const char* value(const ::std_srvs::SetUint32&) { return value(); }
};

template<>
struct DataType< ::std_srvs::SetUint32 > {
  static const char* value()
  {
    return "std_srvs/SetUint32";
  }

  static const char* value(const ::std_srvs::SetUint32&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::SetUint32Request> should match
// service_traits::MD5Sum< ::std_srvs::SetUint32 >
template<>
struct MD5Sum< ::std_srvs::SetUint32Request>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetUint32 >::value();
  }
  static const char* value(const ::std_srvs::SetUint32Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetUint32Request> should match
// service_traits::DataType< ::std_srvs::SetUint32 >
template<>
struct DataType< ::std_srvs::SetUint32Request>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetUint32 >::value();
  }
  static const char* value(const ::std_srvs::SetUint32Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::SetUint32Response> should match
// service_traits::MD5Sum< ::std_srvs::SetUint32 >
template<>
struct MD5Sum< ::std_srvs::SetUint32Response>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetUint32 >::value();
  }
  static const char* value(const ::std_srvs::SetUint32Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetUint32Response> should match
// service_traits::DataType< ::std_srvs::SetUint32 >
template<>
struct DataType< ::std_srvs::SetUint32Response>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetUint32 >::value();
  }
  static const char* value(const ::std_srvs::SetUint32Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETUINT32_H
