// Generated by gencpp from file std_srvs/SetUint8WithTitle.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETUINT8WITHTITLE_H
#define STD_SRVS_MESSAGE_SETUINT8WITHTITLE_H

#include <ros/service_traits.h>


#include <std_srvs/SetUint8WithTitleRequest.h>
#include <std_srvs/SetUint8WithTitleResponse.h>


namespace std_srvs
{

struct SetUint8WithTitle
{

typedef SetUint8WithTitleRequest Request;
typedef SetUint8WithTitleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetUint8WithTitle
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::SetUint8WithTitle > {
  static const char* value()
  {
    return "18bc0bf60ea4ce493a8c7214171ad968";
  }

  static const char* value(const ::std_srvs::SetUint8WithTitle&) { return value(); }
};

template<>
struct DataType< ::std_srvs::SetUint8WithTitle > {
  static const char* value()
  {
    return "std_srvs/SetUint8WithTitle";
  }

  static const char* value(const ::std_srvs::SetUint8WithTitle&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::SetUint8WithTitleRequest> should match
// service_traits::MD5Sum< ::std_srvs::SetUint8WithTitle >
template<>
struct MD5Sum< ::std_srvs::SetUint8WithTitleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetUint8WithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetUint8WithTitleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetUint8WithTitleRequest> should match
// service_traits::DataType< ::std_srvs::SetUint8WithTitle >
template<>
struct DataType< ::std_srvs::SetUint8WithTitleRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetUint8WithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetUint8WithTitleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::SetUint8WithTitleResponse> should match
// service_traits::MD5Sum< ::std_srvs::SetUint8WithTitle >
template<>
struct MD5Sum< ::std_srvs::SetUint8WithTitleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetUint8WithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetUint8WithTitleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetUint8WithTitleResponse> should match
// service_traits::DataType< ::std_srvs::SetUint8WithTitle >
template<>
struct DataType< ::std_srvs::SetUint8WithTitleResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetUint8WithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetUint8WithTitleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETUINT8WITHTITLE_H
