// Generated by gencpp from file std_srvs/SetUint32Array.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETUINT32ARRAY_H
#define STD_SRVS_MESSAGE_SETUINT32ARRAY_H

#include <ros/service_traits.h>


#include <std_srvs/SetUint32ArrayRequest.h>
#include <std_srvs/SetUint32ArrayResponse.h>


namespace std_srvs
{

struct SetUint32Array
{

typedef SetUint32ArrayRequest Request;
typedef SetUint32ArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetUint32Array
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::SetUint32Array > {
  static const char* value()
  {
    return "4587dc15de6ca63e475de8265ece26e9";
  }

  static const char* value(const ::std_srvs::SetUint32Array&) { return value(); }
};

template<>
struct DataType< ::std_srvs::SetUint32Array > {
  static const char* value()
  {
    return "std_srvs/SetUint32Array";
  }

  static const char* value(const ::std_srvs::SetUint32Array&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::SetUint32ArrayRequest> should match
// service_traits::MD5Sum< ::std_srvs::SetUint32Array >
template<>
struct MD5Sum< ::std_srvs::SetUint32ArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetUint32Array >::value();
  }
  static const char* value(const ::std_srvs::SetUint32ArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetUint32ArrayRequest> should match
// service_traits::DataType< ::std_srvs::SetUint32Array >
template<>
struct DataType< ::std_srvs::SetUint32ArrayRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetUint32Array >::value();
  }
  static const char* value(const ::std_srvs::SetUint32ArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::SetUint32ArrayResponse> should match
// service_traits::MD5Sum< ::std_srvs::SetUint32Array >
template<>
struct MD5Sum< ::std_srvs::SetUint32ArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetUint32Array >::value();
  }
  static const char* value(const ::std_srvs::SetUint32ArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetUint32ArrayResponse> should match
// service_traits::DataType< ::std_srvs::SetUint32Array >
template<>
struct DataType< ::std_srvs::SetUint32ArrayResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetUint32Array >::value();
  }
  static const char* value(const ::std_srvs::SetUint32ArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETUINT32ARRAY_H
