// Generated by gencpp from file std_srvs/SetUint8ArrayWithTitle.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_SETUINT8ARRAYWITHTITLE_H
#define STD_SRVS_MESSAGE_SETUINT8ARRAYWITHTITLE_H

#include <ros/service_traits.h>


#include <std_srvs/SetUint8ArrayWithTitleRequest.h>
#include <std_srvs/SetUint8ArrayWithTitleResponse.h>


namespace std_srvs
{

struct SetUint8ArrayWithTitle
{

typedef SetUint8ArrayWithTitleRequest Request;
typedef SetUint8ArrayWithTitleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetUint8ArrayWithTitle
} // namespace std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_srvs::SetUint8ArrayWithTitle > {
  static const char* value()
  {
    return "37b212159fedfb1ad0ae99339700176d";
  }

  static const char* value(const ::std_srvs::SetUint8ArrayWithTitle&) { return value(); }
};

template<>
struct DataType< ::std_srvs::SetUint8ArrayWithTitle > {
  static const char* value()
  {
    return "std_srvs/SetUint8ArrayWithTitle";
  }

  static const char* value(const ::std_srvs::SetUint8ArrayWithTitle&) { return value(); }
};


// service_traits::MD5Sum< ::std_srvs::SetUint8ArrayWithTitleRequest> should match
// service_traits::MD5Sum< ::std_srvs::SetUint8ArrayWithTitle >
template<>
struct MD5Sum< ::std_srvs::SetUint8ArrayWithTitleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetUint8ArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetUint8ArrayWithTitleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetUint8ArrayWithTitleRequest> should match
// service_traits::DataType< ::std_srvs::SetUint8ArrayWithTitle >
template<>
struct DataType< ::std_srvs::SetUint8ArrayWithTitleRequest>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetUint8ArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetUint8ArrayWithTitleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_srvs::SetUint8ArrayWithTitleResponse> should match
// service_traits::MD5Sum< ::std_srvs::SetUint8ArrayWithTitle >
template<>
struct MD5Sum< ::std_srvs::SetUint8ArrayWithTitleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_srvs::SetUint8ArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetUint8ArrayWithTitleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_srvs::SetUint8ArrayWithTitleResponse> should match
// service_traits::DataType< ::std_srvs::SetUint8ArrayWithTitle >
template<>
struct DataType< ::std_srvs::SetUint8ArrayWithTitleResponse>
{
  static const char* value()
  {
    return DataType< ::std_srvs::SetUint8ArrayWithTitle >::value();
  }
  static const char* value(const ::std_srvs::SetUint8ArrayWithTitleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETUINT8ARRAYWITHTITLE_H
