// Generated by gencpp from file controller_msgs/IMUData.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MSGS_MESSAGE_IMUDATA_H
#define CONTROLLER_MSGS_MESSAGE_IMUDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace controller_msgs
{
template <class ContainerAllocator>
struct IMUData_
{
  typedef IMUData_<ContainerAllocator> Type;

  IMUData_()
    : header()
    , imustamp(0)
    , status(0)
    , euler()
    , quat()
    , acc()
    , gyro()  {
      euler.assign(0.0);

      quat.assign(0.0);

      acc.assign(0.0);

      gyro.assign(0.0);
  }
  IMUData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , imustamp(0)
    , status(0)
    , euler()
    , quat()
    , acc()
    , gyro()  {
  (void)_alloc;
      euler.assign(0.0);

      quat.assign(0.0);

      acc.assign(0.0);

      gyro.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _imustamp_type;
  _imustamp_type imustamp;

   typedef uint32_t _status_type;
  _status_type status;

   typedef boost::array<double, 3>  _euler_type;
  _euler_type euler;

   typedef boost::array<double, 4>  _quat_type;
  _quat_type quat;

   typedef boost::array<double, 3>  _acc_type;
  _acc_type acc;

   typedef boost::array<double, 3>  _gyro_type;
  _gyro_type gyro;





  typedef boost::shared_ptr< ::controller_msgs::IMUData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller_msgs::IMUData_<ContainerAllocator> const> ConstPtr;

}; // struct IMUData_

typedef ::controller_msgs::IMUData_<std::allocator<void> > IMUData;

typedef boost::shared_ptr< ::controller_msgs::IMUData > IMUDataPtr;
typedef boost::shared_ptr< ::controller_msgs::IMUData const> IMUDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller_msgs::IMUData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller_msgs::IMUData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::controller_msgs::IMUData_<ContainerAllocator1> & lhs, const ::controller_msgs::IMUData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.imustamp == rhs.imustamp &&
    lhs.status == rhs.status &&
    lhs.euler == rhs.euler &&
    lhs.quat == rhs.quat &&
    lhs.acc == rhs.acc &&
    lhs.gyro == rhs.gyro;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::controller_msgs::IMUData_<ContainerAllocator1> & lhs, const ::controller_msgs::IMUData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace controller_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::controller_msgs::IMUData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller_msgs::IMUData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller_msgs::IMUData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller_msgs::IMUData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller_msgs::IMUData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller_msgs::IMUData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller_msgs::IMUData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4713fbd787897a0c91a2a31aa6a873c6";
  }

  static const char* value(const ::controller_msgs::IMUData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4713fbd787897a0cULL;
  static const uint64_t static_value2 = 0x91a2a31aa6a873c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::controller_msgs::IMUData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller_msgs/IMUData";
  }

  static const char* value(const ::controller_msgs::IMUData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller_msgs::IMUData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint64 imustamp\n"
"uint32 status\n"
"\n"
"float64[3] euler\n"
"float64[4] quat\n"
"float64[3] acc\n"
"float64[3] gyro\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::controller_msgs::IMUData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller_msgs::IMUData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.imustamp);
      stream.next(m.status);
      stream.next(m.euler);
      stream.next(m.quat);
      stream.next(m.acc);
      stream.next(m.gyro);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IMUData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller_msgs::IMUData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller_msgs::IMUData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imustamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.imustamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.status);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "euler: ";
    if (v.euler.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.euler.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.euler[i]);
    }
    if (v.euler.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "quat: ";
    if (v.quat.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.quat.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.quat[i]);
    }
    if (v.quat.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc: ";
    if (v.acc.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.acc.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.acc[i]);
    }
    if (v.acc.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gyro: ";
    if (v.gyro.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.gyro.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.gyro[i]);
    }
    if (v.gyro.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MSGS_MESSAGE_IMUDATA_H
