// Generated by gencpp from file controller_msgs/JointCmdLimx.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MSGS_MESSAGE_JOINTCMDLIMX_H
#define CONTROLLER_MSGS_MESSAGE_JOINTCMDLIMX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace controller_msgs
{
template <class ContainerAllocator>
struct JointCmdLimx_
{
  typedef JointCmdLimx_<ContainerAllocator> Type;

  JointCmdLimx_()
    : header()
    , names()
    , q()
    , v()
    , tau()
    , kp()
    , kd()
    , mode()
    , na(0)
    , parallel_solver_mode()  {
    }
  JointCmdLimx_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , names(_alloc)
    , q(_alloc)
    , v(_alloc)
    , tau(_alloc)
    , kp(_alloc)
    , kd(_alloc)
    , mode(_alloc)
    , na(0)
    , parallel_solver_mode(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _names_type;
  _names_type names;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _q_type;
  _q_type q;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _v_type;
  _v_type v;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _tau_type;
  _tau_type tau;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _kp_type;
  _kp_type kp;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _kd_type;
  _kd_type kd;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _mode_type;
  _mode_type mode;

   typedef uint32_t _na_type;
  _na_type na;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _parallel_solver_mode_type;
  _parallel_solver_mode_type parallel_solver_mode;





  typedef boost::shared_ptr< ::controller_msgs::JointCmdLimx_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller_msgs::JointCmdLimx_<ContainerAllocator> const> ConstPtr;

}; // struct JointCmdLimx_

typedef ::controller_msgs::JointCmdLimx_<std::allocator<void> > JointCmdLimx;

typedef boost::shared_ptr< ::controller_msgs::JointCmdLimx > JointCmdLimxPtr;
typedef boost::shared_ptr< ::controller_msgs::JointCmdLimx const> JointCmdLimxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller_msgs::JointCmdLimx_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller_msgs::JointCmdLimx_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::controller_msgs::JointCmdLimx_<ContainerAllocator1> & lhs, const ::controller_msgs::JointCmdLimx_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.names == rhs.names &&
    lhs.q == rhs.q &&
    lhs.v == rhs.v &&
    lhs.tau == rhs.tau &&
    lhs.kp == rhs.kp &&
    lhs.kd == rhs.kd &&
    lhs.mode == rhs.mode &&
    lhs.na == rhs.na &&
    lhs.parallel_solver_mode == rhs.parallel_solver_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::controller_msgs::JointCmdLimx_<ContainerAllocator1> & lhs, const ::controller_msgs::JointCmdLimx_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace controller_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::controller_msgs::JointCmdLimx_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller_msgs::JointCmdLimx_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller_msgs::JointCmdLimx_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller_msgs::JointCmdLimx_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller_msgs::JointCmdLimx_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller_msgs::JointCmdLimx_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller_msgs::JointCmdLimx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa66c708f26b270ba9c935d9e8db6182";
  }

  static const char* value(const ::controller_msgs::JointCmdLimx_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa66c708f26b270bULL;
  static const uint64_t static_value2 = 0xa9c935d9e8db6182ULL;
};

template<class ContainerAllocator>
struct DataType< ::controller_msgs::JointCmdLimx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller_msgs/JointCmdLimx";
  }

  static const char* value(const ::controller_msgs::JointCmdLimx_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller_msgs::JointCmdLimx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"string[]  names\n"
"float32[] q\n"
"float32[] v\n"
"float32[] tau\n"
"float32[] kp\n"
"float32[] kd\n"
"uint8[] mode\n"
"uint32 na\n"
"uint8[] parallel_solver_mode\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::controller_msgs::JointCmdLimx_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller_msgs::JointCmdLimx_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.names);
      stream.next(m.q);
      stream.next(m.v);
      stream.next(m.tau);
      stream.next(m.kp);
      stream.next(m.kd);
      stream.next(m.mode);
      stream.next(m.na);
      stream.next(m.parallel_solver_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointCmdLimx_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller_msgs::JointCmdLimx_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller_msgs::JointCmdLimx_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "names: ";
    if (v.names.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.names[i]);
    }
    if (v.names.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "q: ";
    if (v.q.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.q.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.q[i]);
    }
    if (v.q.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v: ";
    if (v.v.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.v.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.v[i]);
    }
    if (v.v.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tau: ";
    if (v.tau.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.tau.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.tau[i]);
    }
    if (v.tau.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "kp: ";
    if (v.kp.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.kp.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.kp[i]);
    }
    if (v.kp.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "kd: ";
    if (v.kd.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.kd.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.kd[i]);
    }
    if (v.kd.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    if (v.mode.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.mode.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.mode[i]);
    }
    if (v.mode.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "na: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.na);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "parallel_solver_mode: ";
    if (v.parallel_solver_mode.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.parallel_solver_mode.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.parallel_solver_mode[i]);
    }
    if (v.parallel_solver_mode.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MSGS_MESSAGE_JOINTCMDLIMX_H
