// Generated by gencpp from file teleop_msgs/TeleopIntentFrame.msg
// DO NOT EDIT!


#ifndef TELEOP_MSGS_MESSAGE_TELEOPINTENTFRAME_H
#define TELEOP_MSGS_MESSAGE_TELEOPINTENTFRAME_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <teleop_msgs/TeleopTarget.h>
#include <teleop_msgs/TeleopRawInput.h>
#include <controller_msgs/JointCmd.h>

namespace teleop_msgs
{
template <class ContainerAllocator>
struct TeleopIntentFrame_
{
  typedef TeleopIntentFrame_<ContainerAllocator> Type;

  TeleopIntentFrame_()
    : header()
    , schema_version(0)
    , source(0)
    , source_mask(0)
    , reference_frame()
    , reference_pose()
    , targets()
    , raw_valid(false)
    , raw()
    , head_control_selected(false)
    , retarget_valid(false)
    , retarget_joints()  {
    }
  TeleopIntentFrame_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , schema_version(0)
    , source(0)
    , source_mask(0)
    , reference_frame(_alloc)
    , reference_pose(_alloc)
    , targets(_alloc)
    , raw_valid(false)
    , raw(_alloc)
    , head_control_selected(false)
    , retarget_valid(false)
    , retarget_joints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _schema_version_type;
  _schema_version_type schema_version;

   typedef uint8_t _source_type;
  _source_type source;

   typedef uint32_t _source_mask_type;
  _source_mask_type source_mask;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reference_frame_type;
  _reference_frame_type reference_frame;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _reference_pose_type;
  _reference_pose_type reference_pose;

   typedef std::vector< ::teleop_msgs::TeleopTarget_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::teleop_msgs::TeleopTarget_<ContainerAllocator> >> _targets_type;
  _targets_type targets;

   typedef uint8_t _raw_valid_type;
  _raw_valid_type raw_valid;

   typedef  ::teleop_msgs::TeleopRawInput_<ContainerAllocator>  _raw_type;
  _raw_type raw;

   typedef uint8_t _head_control_selected_type;
  _head_control_selected_type head_control_selected;

   typedef uint8_t _retarget_valid_type;
  _retarget_valid_type retarget_valid;

   typedef  ::controller_msgs::JointCmd_<ContainerAllocator>  _retarget_joints_type;
  _retarget_joints_type retarget_joints;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SCHEMA_VERSION)
  #undef SCHEMA_VERSION
#endif
#if defined(_WIN32) && defined(SOURCE_UNKNOWN)
  #undef SOURCE_UNKNOWN
#endif
#if defined(_WIN32) && defined(SOURCE_VR)
  #undef SOURCE_VR
#endif
#if defined(_WIN32) && defined(SOURCE_MOCAP)
  #undef SOURCE_MOCAP
#endif
#if defined(_WIN32) && defined(SOURCE_GLOVE)
  #undef SOURCE_GLOVE
#endif
#if defined(_WIN32) && defined(SOURCE_FUSED)
  #undef SOURCE_FUSED
#endif

  enum {
    SCHEMA_VERSION = 1u,
    SOURCE_UNKNOWN = 0u,
    SOURCE_VR = 1u,
    SOURCE_MOCAP = 2u,
    SOURCE_GLOVE = 3u,
    SOURCE_FUSED = 4u,
  };


  typedef boost::shared_ptr< ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator> const> ConstPtr;

}; // struct TeleopIntentFrame_

typedef ::teleop_msgs::TeleopIntentFrame_<std::allocator<void> > TeleopIntentFrame;

typedef boost::shared_ptr< ::teleop_msgs::TeleopIntentFrame > TeleopIntentFramePtr;
typedef boost::shared_ptr< ::teleop_msgs::TeleopIntentFrame const> TeleopIntentFrameConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator1> & lhs, const ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.schema_version == rhs.schema_version &&
    lhs.source == rhs.source &&
    lhs.source_mask == rhs.source_mask &&
    lhs.reference_frame == rhs.reference_frame &&
    lhs.reference_pose == rhs.reference_pose &&
    lhs.targets == rhs.targets &&
    lhs.raw_valid == rhs.raw_valid &&
    lhs.raw == rhs.raw &&
    lhs.head_control_selected == rhs.head_control_selected &&
    lhs.retarget_valid == rhs.retarget_valid &&
    lhs.retarget_joints == rhs.retarget_joints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator1> & lhs, const ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace teleop_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3147143ffcdf2121d4c65dce9c5f350";
  }

  static const char* value(const ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3147143ffcdf212ULL;
  static const uint64_t static_value2 = 0x1d4c65dce9c5f350ULL;
};

template<class ContainerAllocator>
struct DataType< ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "teleop_msgs/TeleopIntentFrame";
  }

  static const char* value(const ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 遥操作意图帧。输入汇聚层每组装出一个操作者帧，发布至多一条本消息。\n"
"# 承载「操作者想做什么」，不承载任何控制决策。\n"
"\n"
"# stamp 为帧组装时刻；seq 为帧序号，供接收方检测丢帧。\n"
"std_msgs/Header header\n"
"\n"
"uint16 SCHEMA_VERSION=1\n"
"uint16 schema_version\n"
"\n"
"# 本帧的主输入源\n"
"uint8 SOURCE_UNKNOWN=0\n"
"uint8 SOURCE_VR=1\n"
"uint8 SOURCE_MOCAP=2\n"
"uint8 SOURCE_GLOVE=3\n"
"uint8 SOURCE_FUSED=4\n"
"uint8 source\n"
"\n"
"# 参与本帧合成的全部输入源，按 1 << SOURCE_* 置位\n"
"uint32 source_mask\n"
"\n"
"# targets 中位姿所在参考系的名称\n"
"string reference_frame\n"
"\n"
"# 当参考系本身是运行时位姿（例如随头部偏航的参考系）时给出其位姿。\n"
"# 参考系为静态具名坐标系时填单位位姿。\n"
"geometry_msgs/Pose reference_pose\n"
"\n"
"# 本帧的跟踪目标。目标缺席即表示该肢体本帧无输入。\n"
"teleop_msgs/TeleopTarget[] targets\n"
"\n"
"# 原始输入是否有效。纯动捕帧没有手柄输入时为 false。\n"
"bool raw_valid\n"
"teleop_msgs/TeleopRawInput raw\n"
"\n"
"# 操作者侧选项：是否选择了「控头」。\n"
"# 来源可能是 VR 应用内的选择，也可能是兼容服务设置，不属于设备原始输入。\n"
"bool head_control_selected\n"
"\n"
"# 全身重定向结果是否有效。是否真正下发由接收方决定。\n"
"bool retarget_valid\n"
"controller_msgs/JointCmd retarget_joints\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: teleop_msgs/TeleopTarget\n"
"# 遥操作中的单个跟踪目标（末端、头、躯干、足等）。\n"
"# 作为 TeleopIntentFrame.targets 的元素使用。\n"
"\n"
"# 目标名。约定值：left_hand / right_hand / head / torso / base /\n"
"# left_foot / right_foot / left_wrist / right_wrist。\n"
"# 新增跟踪目标只需约定新名字，不需要改本消息。\n"
"string name\n"
"\n"
"# 目标位姿。参考系由 TeleopIntentFrame.reference_frame 指定。\n"
"geometry_msgs/Pose pose\n"
"\n"
"# 数据可信度。接收方据此决定跟随、降级还是忽略。\n"
"uint8 VALIDITY_INVALID=0       # 非法，接收方必须忽略\n"
"uint8 VALIDITY_VALID=1         # 新鲜可用\n"
"uint8 VALIDITY_STALE=2         # 有数据但已超期\n"
"uint8 VALIDITY_EXTRAPOLATED=3  # 由外推得到，非实测\n"
"uint8 validity\n"
"\n"
"# 该目标数据的采集时刻。与帧组装时刻（header.stamp）可能不同，\n"
"# 接收方据此判断单个目标的新鲜度。\n"
"time source_stamp\n"
"\n"
"================================================================================\n"
"MSG: teleop_msgs/TeleopRawInput\n"
"# 操作者控制器的原始输入量。\n"
"# 发送方不解释任何按键含义，组合键语义一律由接收方解释。\n"
"\n"
"# 模拟量，范围 0.0 ~ 1.0\n"
"float32 left_trigger\n"
"float32 right_trigger\n"
"float32 left_grip\n"
"float32 right_grip\n"
"\n"
"# 摇杆，[x, y]，范围 -1.0 ~ 1.0\n"
"float32[2] left_stick\n"
"float32[2] right_stick\n"
"\n"
"# 按键位掩码。预留高位，新增按键不需要改本消息。\n"
"uint32 BTN_LEFT_X=1\n"
"uint32 BTN_LEFT_Y=2\n"
"uint32 BTN_RIGHT_A=4\n"
"uint32 BTN_RIGHT_B=8\n"
"uint32 BTN_LEFT_STICK=16         # 左摇杆按下\n"
"uint32 BTN_RIGHT_STICK=32        # 右摇杆按下\n"
"uint32 BTN_LEFT_GRIP=64          # 左 Grip 的布尔态\n"
"uint32 BTN_RIGHT_GRIP=128        # 右 Grip 的布尔态\n"
"uint32 BTN_LEFT_TRIGGER=256      # 左扳机的布尔态\n"
"uint32 BTN_RIGHT_TRIGGER=512     # 右扳机的布尔态\n"
"uint32 BTN_LEFT_THUMBREST=1024\n"
"uint32 BTN_RIGHT_THUMBREST=2048\n"
"uint32 buttons\n"
"\n"
"# 哪些按键位本帧有效。设备不提供的按键，对应位为 0。\n"
"# 接收方不得把「设备未提供」当成「按键未按下」。\n"
"uint32 buttons_valid\n"
"\n"
"================================================================================\n"
"MSG: controller_msgs/JointCmd\n"
"std_msgs/Header header\n"
"\n"
"string[]  names\n"
"float32[] q\n"
"float32[] v\n"
"float32[] tau\n"
"float32[] kp\n"
"float32[] kd\n"
"uint8[] mode\n"
"uint32 na\n"
;
  }

  static const char* value(const ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.schema_version);
      stream.next(m.source);
      stream.next(m.source_mask);
      stream.next(m.reference_frame);
      stream.next(m.reference_pose);
      stream.next(m.targets);
      stream.next(m.raw_valid);
      stream.next(m.raw);
      stream.next(m.head_control_selected);
      stream.next(m.retarget_valid);
      stream.next(m.retarget_joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TeleopIntentFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::teleop_msgs::TeleopIntentFrame_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "schema_version: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.schema_version);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "source: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.source);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "source_mask: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.source_mask);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reference_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reference_frame);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reference_pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.reference_pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "targets: ";
    if (v.targets.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.targets.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::teleop_msgs::TeleopTarget_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.targets[i]);
    }
    if (v.targets.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "raw_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.raw_valid);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "raw: ";
    Printer< ::teleop_msgs::TeleopRawInput_<ContainerAllocator> >::stream(s, indent + "  ", v.raw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "head_control_selected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.head_control_selected);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "retarget_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.retarget_valid);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "retarget_joints: ";
    Printer< ::controller_msgs::JointCmd_<ContainerAllocator> >::stream(s, indent + "  ", v.retarget_joints);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TELEOP_MSGS_MESSAGE_TELEOPINTENTFRAME_H
