// Generated by gencpp from file hand_msgs/HandMsg.msg
// DO NOT EDIT!


#ifndef HAND_MSGS_MESSAGE_HANDMSG_H
#define HAND_MSGS_MESSAGE_HANDMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace hand_msgs
{
template <class ContainerAllocator>
struct HandMsg_
{
  typedef HandMsg_<ContainerAllocator> Type;

  HandMsg_()
    : header()
    , names()
    , pos()
    , vel()
    , current()
    , time()  {
    }
  HandMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , names(_alloc)
    , pos(_alloc)
    , vel(_alloc)
    , current(_alloc)
    , time(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _names_type;
  _names_type names;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _pos_type;
  _pos_type pos;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _vel_type;
  _vel_type vel;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _current_type;
  _current_type current;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::hand_msgs::HandMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_msgs::HandMsg_<ContainerAllocator> const> ConstPtr;

}; // struct HandMsg_

typedef ::hand_msgs::HandMsg_<std::allocator<void> > HandMsg;

typedef boost::shared_ptr< ::hand_msgs::HandMsg > HandMsgPtr;
typedef boost::shared_ptr< ::hand_msgs::HandMsg const> HandMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_msgs::HandMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_msgs::HandMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hand_msgs::HandMsg_<ContainerAllocator1> & lhs, const ::hand_msgs::HandMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.names == rhs.names &&
    lhs.pos == rhs.pos &&
    lhs.vel == rhs.vel &&
    lhs.current == rhs.current &&
    lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hand_msgs::HandMsg_<ContainerAllocator1> & lhs, const ::hand_msgs::HandMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hand_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hand_msgs::HandMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_msgs::HandMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_msgs::HandMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_msgs::HandMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_msgs::HandMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_msgs::HandMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_msgs::HandMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5bf399d0b94663b56e927d0e9c254c1c";
  }

  static const char* value(const ::hand_msgs::HandMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5bf399d0b94663b5ULL;
  static const uint64_t static_value2 = 0x6e927d0e9c254c1cULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_msgs::HandMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_msgs/HandMsg";
  }

  static const char* value(const ::hand_msgs::HandMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_msgs::HandMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"string[]  names\n"
"float32[] pos\n"
"float32[] vel\n"
"float32[] current\n"
"float32[] time\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::hand_msgs::HandMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_msgs::HandMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.names);
      stream.next(m.pos);
      stream.next(m.vel);
      stream.next(m.current);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HandMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_msgs::HandMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_msgs::HandMsg_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "names: ";
    if (v.names.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.names[i]);
    }
    if (v.names.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pos: ";
    if (v.pos.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.pos[i]);
    }
    if (v.pos.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vel: ";
    if (v.vel.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.vel.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.vel[i]);
    }
    if (v.vel.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current: ";
    if (v.current.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.current.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.current[i]);
    }
    if (v.current.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "time: ";
    if (v.time.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.time.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.time[i]);
    }
    if (v.time.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_MSGS_MESSAGE_HANDMSG_H
